import Database from 'better-sqlite3';
import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {CodexWorker,workerServer,listenWorker} from '../../../packages/agents/src/worker.js';
const directory=process.env.CODEX_WORKER_DATA??'/var/lib/agentic-codex-worker';
mkdirSync(directory,{recursive:true,mode:0o700});
const db=new Database(join(directory,'tasks.db'));
const worker=new CodexWorker(db,process.env.CODEX_TRUSTED_DIRECTORY??process.cwd());
const server=workerServer(worker);
await listenWorker(server,process.env.CODEX_WORKER_SOCKET??'/run/agentic-codex-worker/worker.sock');worker.start();
for(const signal of ['SIGINT','SIGTERM'] as const)process.once(signal,()=>{void(async()=>{await worker.stop();await server.close();db.close();process.exit(0);})();});
