import {z} from 'zod';
import {afterEach,describe,it,expect,vi} from 'vitest';
import Database from 'better-sqlite3';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {CodexRunner,isolatedConfig,safeCodexEnvironment} from '../packages/agents/src/codex-runner.js';
import {CodexWorker,workerServer,probeCodex,failureCode,type WorkerJob} from '../packages/agents/src/worker.js';
import {CodexTaskService,scheduleInput} from '../packages/agents/src/task-service.js';
import {taskInput,taskResponse,defaultSettings,validateAuthority,classify,type TaskInput,type TaskResponse} from '../packages/agents/src/task-contract.js';
import {AgenticManager} from '../packages/core/src/agentic-manager.js';
import {exampleProposal} from '../packages/trading-v2/src/self-tests.js';
import type {WorkerTransport} from '../packages/agents/src/worker-client.js';
import {OpenAIResponsesTransport} from '../packages/trading-v2/src/agent.js';
const cleanup:Array<()=>void|Promise<void>>=[];
afterEach(async()=>{while(cleanup.length)await cleanup.pop()?.();vi.restoreAllMocks();vi.unstubAllEnvs();});
const healthy=async()=>({installed:true,version:'codex-cli 0.157.1',loggedIn:true,compatible:true,usable:true,robinhood:{configured:false,state:'MCP_UNAVAILABLE' as const,status:'Robinhood MCP unavailable'},checkedAt:new Date().toISOString()});
const response:TaskResponse={kind:'NaturalLanguageResponse',message:'Stored account reviewed; broker facts are unavailable.',action:null,sources:[]};
const input=(id='task-1'):TaskInput=>({id,message:'Review my account',type:'FREE_FORM_USER_REQUEST',authority:'READ_ONLY',strategy:null,context:'{}',settings:defaultSettings});
function fixtureWorker(output:TaskResponse=response){const db=new Database(':memory:'),runner=new CodexRunner();vi.spyOn(runner,'run').mockImplementation(async r=>({requestId:r.requestId!,value:r.validate(output),durationMs:1,attempts:1,stderr:'',metadata:{}}));const w=new CodexWorker(db,process.cwd(),runner,healthy);cleanup.push(async()=>{await w.stop();db.close();});return {w,db,runner};}
function completed(id:string,output=response):WorkerJob{return {id,status:'COMPLETED',createdAt:new Date().toISOString(),startedAt:new Date().toISOString(),endedAt:new Date().toISOString(),response:output,error:null,stdout:'',stderr:'',version:'codex-cli 0.157.1',hash:null,durationMs:1};}
async function app(output=response){const m=new AgenticManager({databasePath:':memory:',workingDirectory:process.cwd(),sessionSecret:'test-secret-with-at-least-thirty-two-characters',startBackgroundServices:false});cleanup.push(()=>m.shutdown());await m.start();const transport:WorkerTransport={health:async()=>({...await healthy(),active:0,queued:0}),enqueue:vi.fn(async task=>completed(task.id,output)),get:vi.fn(async id=>completed(id,output)),cancel:vi.fn(async id=>({...completed(id),status:'CANCELLED' as const}))};const s=new CodexTaskService(m.database,m.proposals,transport);return {m,s,transport};}
describe('Bounded Codex worker',()=>{
 it('omits unavailable broker MCP from stored-context tasks',async()=>{const {w,runner}=fixtureWorker();vi.spyOn(w,'health').mockResolvedValue({...await healthy(),active:0,queued:0,robinhood:{configured:true,state:'CREDENTIAL_STORE_UNAVAILABLE',status:'Credential store unavailable'}});w.enqueue(input());await w.tick();await vi.waitFor(()=>expect(w.get('task-1').status).toBe('COMPLETED'));expect(runner.run).toHaveBeenCalledWith(expect.objectContaining({robinhoodReads:false,prompt:expect.stringContaining('Use supplied stored context only')}));});
 it('fails broker-dependent work clearly without invoking Codex when auth is unavailable',async()=>{const {w,runner}=fixtureWorker();vi.spyOn(w,'health').mockResolvedValue({...await healthy(),active:0,queued:0,robinhood:{configured:true,state:'NEEDS_LOGIN',status:'Needs login'}});w.enqueue({...input(),type:'RESEARCH_SYMBOL',authority:'RESEARCH'});await w.tick();await vi.waitFor(()=>expect(w.get('task-1').status).toBe('FAILED'));expect(w.get('task-1').error).toContain('ROBINHOOD_NEEDS_LOGIN');expect(runner.run).not.toHaveBeenCalled();});
 it('emits CLI-compatible anyOf while validating strict action variants',()=>{const schema=JSON.stringify(z.toJSONSchema(taskResponse,{target:'draft-7'}));expect(schema).not.toContain('oneOf');expect(schema).toContain('anyOf');});
 it('builds the worker as part of every production build',()=>{const manifest=JSON.parse(readFileSync('package.json','utf8'));expect(manifest.scripts.build).toContain('npm run build:worker');expect(manifest.scripts['build:worker']).toContain('apps/worker/src/index.ts');});
 it('detects missing CLI without invoking a model or network fallback',async()=>{expect(await probeCodex('nonexistent-codex-fixture')).toMatchObject({installed:false,loggedIn:false,usable:false,robinhood:{configured:false}});});
 it('excludes API credentials and execution tools from child environment and capabilities',()=>{vi.stubEnv('OPENAI_API_KEY','secret');vi.stubEnv('CODEX_API_KEY','secret');expect(safeCodexEnvironment()).not.toHaveProperty('OPENAI_API_KEY');expect(safeCodexEnvironment()).not.toHaveProperty('CODEX_API_KEY');const flags=isolatedConfig({robinhoodReads:true}).join(' ');expect(flags).toContain('features.shell_tool=false');expect(flags).toContain('features.plugins=false');expect(flags).toContain('enabled_tools=');expect(flags).not.toMatch(/place_order|cancel_order|transfer_funds/);});
 it('rejects arbitrary flags, shell, URLs and execution authority in worker payloads',()=>{for(const extra of [{flags:['--dangerously-bypass-approvals-and-sandbox']},{cwd:'/'},{shell:'rm -rf /'},{authority:'EXECUTION_ALLOWED'}])expect(()=>taskInput.parse({...input(),...extra})).toThrow();expect(()=>taskInput.parse({...input(),settings:{...defaultSettings,model:'foo --flag'}})).toThrow();});
 it('rejects malformed or unknown financial intents',()=>{expect(()=>taskResponse.parse({...response,action:{intent:'place_order'}})).toThrow();expect(()=>taskResponse.parse({message:'hello'})).toThrow();});
 it('independently enforces task authority and strategy target',()=>{const pause={...response,action:{intent:'pause_strategy' as const,strategy:'OPTIONS' as const,reason:'Operator request'}};expect(()=>validateAuthority(input(),pause)).toThrow('AUTHORITY_DENIED');expect(()=>validateAuthority({...input(),authority:'CONFIGURE_PROPOSAL',strategy:'SAFE_LONG_TERM'},pause)).toThrow('TARGET_MISMATCH');});
 it('completes read jobs without a broker and stores validated output/hash',async()=>{const {w}=fixtureWorker();w.enqueue(input());await w.tick();await vi.waitFor(()=>expect(w.get('task-1').status).toBe('COMPLETED'));expect(w.get('task-1').hash).toHaveLength(64);});
 it('deduplicates identical IDs and rejects changed input',()=>{const {w}=fixtureWorker();w.enqueue(input());w.enqueue(input());expect(w.list()).toHaveLength(1);expect(()=>w.enqueue({...input(),message:'Different'})).toThrow('Duplicate');});
 it('rejects authority violations returned by a worker model',async()=>{const {w}=fixtureWorker({...response,action:{intent:'pause_all',reason:'unexpected'}});w.enqueue(input());await w.tick();await vi.waitFor(()=>expect(w.get('task-1').status).toBe('FAILED'));});
 it.each(['usage limit exceeded','quota unavailable','rate limit'])('marks %s without replay',async message=>{const {w,runner}=fixtureWorker();vi.mocked(runner.run).mockRejectedValue(new Error(message));w.enqueue(input());await w.tick();await vi.waitFor(()=>expect(w.get('task-1').status).toBe('BLOCKED_USAGE_LIMIT'));await w.tick();expect(runner.run).toHaveBeenCalledTimes(1);});
 it('cancels queued tasks without spawning Codex',async()=>{const {w,runner}=fixtureWorker();w.enqueue(input());w.cancel('task-1');await w.tick();expect(runner.run).not.toHaveBeenCalled();expect(w.get('task-1').status).toBe('CANCELLED');});
 it('enforces concurrency and cancels active work',async()=>{const {w,runner}=fixtureWorker();vi.mocked(runner.run).mockImplementation(r=>new Promise((_resolve,reject)=>{if(r.signal?.aborted)reject(new Error('cancelled'));else r.signal?.addEventListener('abort',()=>reject(new Error('cancelled')));}));w.enqueue(input('a'));w.enqueue(input('b'));await w.tick();await vi.waitFor(()=>expect(runner.run).toHaveBeenCalledTimes(1));expect(w.get('b').status).toBe('QUEUED');w.cancel('a');await vi.waitFor(()=>expect(w.get('a').status).toBe('CANCELLED'));});
 it('recovers interrupted persisted jobs as UNKNOWN and never replays',()=>{const dir=mkdtempSync(join(tmpdir(),'codex-recovery-'));cleanup.push(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'tasks.db'),db=new Database(path),w=new CodexWorker(db,process.cwd());w.enqueue(input());const job={...w.get('task-1'),status:'RUNNING'};db.prepare('UPDATE codex_worker_jobs SET body_json=? WHERE id=?').run(JSON.stringify(job),job.id);db.close();const reopened=new Database(path),recovered=new CodexWorker(reopened,process.cwd());expect(recovered.get(job.id).status).toBe('UNKNOWN');reopened.close();});
 it('IPC exposes only bounded job endpoints',async()=>{const {w}=fixtureWorker(),server=workerServer(w);cleanup.push(()=>server.close());expect((await server.inject({method:'POST',url:'/shell',payload:{cmd:'id'}})).statusCode).toBe(404);expect((await server.inject({method:'POST',url:'/jobs',payload:{...input(),flags:[]}})).statusCode).not.toBe(200);expect((await server.inject({method:'POST',url:'/jobs',payload:input()})).statusCode).toBe(200);});
 it('uses an encrypted headless keyring and isolated service identities',()=>{const unit=readFileSync('systemd/agentic-codex-worker.service','utf8'),installer=readFileSync('scripts/pi-worker-install.sh','utf8'),entry=readFileSync('scripts/codex-worker-entrypoint.sh','utf8'),worker=readFileSync('packages/agents/src/worker.ts','utf8');expect(unit).toContain('User=cadenlenz');expect(unit).toContain('LoadCredentialEncrypted=keyring-passphrase:');expect(unit).toContain('XDG_DATA_HOME=/var/lib/agentic-codex-worker/xdg');expect(unit).toContain('InaccessiblePaths=/var/lib/agentic-trading-manager');expect(installer).toContain('systemd-creds encrypt');expect(installer).toContain('SupplementaryGroups=agentic-codex');expect(entry).toContain('dbus-run-session');expect(entry).toContain('gnome-keyring-daemon --unlock');expect(worker).toContain('mcp_oauth_credentials_store=');expect(worker).toContain('chmod(socket,0o660)');expect([unit,installer,entry].join('\n')).not.toMatch(/1BigNose|access_token|refresh_token/);});
 it('does not persist OAuth material in worker SQLite',()=>{const {w,db}=fixtureWorker();w.enqueue(input());expect(JSON.stringify(db.prepare('SELECT * FROM codex_worker_jobs').all())).not.toMatch(/access_token|refresh_token|Bearer /i);});
 it('classifies timeout and cancellation distinctly',()=>{expect(failureCode('timed out')).toBe('TIMED_OUT');expect(failureCode('Codex run canceled')).toBe('CANCELLED');expect(failureCode('Prompt says no cancellation; invalid schema')).toBe('FAILED');});
});
describe('Application authority, audit and scheduling',()=>{
 it('keeps read-only tasks read-only and audits completion',async()=>{const {m,s}=await app();const task=s.create('Review my account','operator');await s.tick();expect(s.get(task.id)).toMatchObject({status:'COMPLETED',applied:true,authority:'READ_ONLY'});expect(m.database.raw.prepare("SELECT id FROM audit_events WHERE action='CODEX_TASK_COMPLETED'").all()).toHaveLength(1);});
 it('pauses a requested sleeve exactly once without Codex controlling execution',async()=>{const {m,s}=await app({...response,action:{intent:'pause_strategy',strategy:'AGGRESSIVE_STOCKS',reason:'User asked to pause'}});const t=s.create('Pause aggressive trading','operator');await s.tick();await s.tick();expect(s.get(t.id).status).toBe('COMPLETED');expect(m.database.getStrategy('AGGRESSIVE_STOCKS')?.enabled).toBe(false);});
 it('validates untrusted worker output again before state changes',async()=>{const {m,s}=await app({...response,action:{intent:'pause_all',reason:'unexpected'}});m.database.setSetting('global_pause',false);const t=s.create('Review account','operator');await s.tick();expect(s.get(t.id).status).toBe('FAILED');expect(m.database.getSetting('global_pause',false)).toBe(false);});
 it('creates draft proposals with no orders, approval or execution bypass',async()=>{const {m,s}=await app({...response,kind:'TradeProposal',action:{intent:'create_trade_proposal',proposal:exampleProposal()}});const t=s.create('Generate a trade proposal','operator');await s.tick();expect(s.get(t.id).status).toBe('COMPLETED');expect(m.proposals.list()[0]?.state).toBe('DRAFT');expect(m.database.raw.prepare('SELECT * FROM orders').all()).toHaveLength(0);await expect(m.proposals.execute(m.proposals.list()[0]!.id,'operator')).rejects.toThrow();});
 it('proposes risk changes requiring independent confirmation',async()=>{const {m,s}=await app({...response,action:{intent:'risk_change_proposal',changes:[{scope:'GLOBAL',strategy:null,assetClass:null,symbol:null,key:'maxOrderNotional',valueJson:'100'}],reason:'Reduce maximum order exposure for operator review'}});const before=m.riskConfiguration.current();const t=s.create('Make options safer','operator');await s.tick();expect(s.get(t.id).status).toBe('COMPLETED');expect(m.riskConfiguration.current()).toEqual(before);expect(m.database.raw.prepare("SELECT id FROM pending_changes WHERE status='PENDING'").all()).toHaveLength(1);});
 it('routes full-system-test intents to the isolated simulation service',async()=>{const {s}=await app({...response,action:{intent:'run_full_simulation'}});s.runSimulation=vi.fn(()=>({id:'isolated-fixture'}));s.create('Run the full system test','operator');await s.tick();expect(s.runSimulation).toHaveBeenCalledTimes(1);});
 it('records uncertain IPC dispatch and does not retry',async()=>{const {s,transport}=await app();vi.mocked(transport.enqueue).mockRejectedValue(new Error('network timeout'));const t=s.create('Summarize today','operator');await s.tick();await s.tick();expect(s.get(t.id).status).toBe('UNKNOWN');expect(transport.enqueue).toHaveBeenCalledTimes(1);});
 it('persists task history across service objects and deduplicates submissions',async()=>{const {m,s,transport}=await app();s.create('Review account','operator',{id:'durable'});await s.tick();const reopened=new CodexTaskService(m.database,m.proposals,transport);expect(reopened.create('Review account','operator',{id:'durable'}).status).toBe('COMPLETED');expect(reopened.list()).toHaveLength(1);});
 it('schedules one bounded occurrence and preserves the next run',async()=>{const {s}=await app();const schedule=s.schedule({name:'Morning review',message:'Review account',type:'DAILY_REPORT',authority:'READ_ONLY',strategy:null,intervalMinutes:1440,enabled:true,timeoutMs:120000},'operator');const at=new Date(Date.parse(schedule.nextRun)+1000);s.tickSchedules(at);s.tickSchedules(at);expect(s.list()).toHaveLength(1);expect(s.list()[0]?.source).toBe('SCHEDULED');expect(Date.parse(s.schedules()[0]!.nextRun)).toBeGreaterThan(at.getTime());});
 it('rejects execution-capable or configuration-mutating schedules',()=>{expect(()=>scheduleInput.parse({name:'bad',message:'trade',type:'FREE_FORM_USER_REQUEST',authority:'EXECUTION_ALLOWED',strategy:null,intervalMinutes:15,enabled:true,timeoutMs:10000})).toThrow();});
 it('never silently falls back to paid OpenAI inference',async()=>{vi.stubEnv('OPENAI_API_KEY','sk-fixture');vi.stubEnv('ENABLE_LEGACY_OPENAI_API','false');const network=vi.spyOn(globalThis,'fetch');await expect(new OpenAIResponsesTransport().respond({})).rejects.toThrow('disabled');expect(network).not.toHaveBeenCalled();});
 it('uses explicit narrow classifications, with no execution class',()=>{expect(classify('Review my account').authority).toBe('READ_ONLY');expect(classify('Pause aggressive trading')).toMatchObject({authority:'CONFIGURE_PROPOSAL',strategy:'AGGRESSIVE_STOCKS'});expect(classify('Generate a trade proposal').authority).toBe('TRADE_PROPOSAL');expect(classify('Buy TSLA immediately').authority).toBe('READ_ONLY');});
});
