import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {AgenticManager} from '../packages/core/src/agentic-manager.js';
import {nowIso} from '../packages/core/src/utils.js';
import {exampleProposal,runSelfTests} from '../packages/trading-v2/src/self-tests.js';
import {RESEARCH_REQUIRED,proposalSchema,SLEEVES,type ProposalInput,type TradingBroker,type ExecutableOrder} from '../packages/trading-v2/src/model.js';
import {PersistentTradingAgent,AGENT_TOOLS} from '../packages/trading-v2/src/agent.js';
import {SimulationTradingBroker} from '../packages/trading-v2/src/broker.js';
import {ProposalService} from '../packages/trading-v2/src/proposals.js';
import {buy} from './helpers.js';
import {prepareEmergencyCloses} from '../packages/trading-v2/src/emergency.js';
const cleanup:Array<()=>Promise<void>>=[];
beforeEach(()=>{vi.stubEnv('OPENAI_API_KEY','');vi.stubEnv('ENABLE_SMS_DELIVERY','false');});
afterEach(async()=>{while(cleanup.length)await cleanup.pop()?.();vi.unstubAllEnvs();});
async function fixture(){const m=new AgenticManager({databasePath:':memory:',workingDirectory:process.cwd(),sessionSecret:'test-secret-with-at-least-thirty-two-characters',startBackgroundServices:false});cleanup.push(()=>m.shutdown());await m.start();return m;}
const research=(strategy:ProposalInput['strategy'])=>({simulated:true,items:RESEARCH_REQUIRED[strategy].map(category=>({category,summary:'Synthetic evidence for deterministic regression testing only.',sources:['https://example.com/synthetic-evidence'],observedAt:nowIso()}))});
async function ready(m:AgenticManager,input:ProposalInput=exampleProposal()){const p=m.proposals.create(input,'test');m.proposals.research(p.id,research(p.strategy),'test');await m.proposals.review(p.id,'test');return m.proposals.get(p.id);}
function option(m:AgenticManager,strategy:'LONG_CALL'|'LONG_PUT'|'COVERED_CALL'|'CASH_SECURED_PUT'='LONG_PUT'):ProposalInput {
  const type=strategy.includes('CALL')?'CALL':'PUT',expiration='2027-01-15',optionId='synthetic-'+strategy;
  m.database.setSetting('global_risk',{...m.database.getGlobalRisk(),optionsEnabled:true});
  m.database.raw.prepare('INSERT OR REPLACE INTO simulation_option_instruments VALUES(?,?,?)').run(optionId,JSON.stringify({optionId,underlying:'TEST',type,strike:10,expiration,multiplier:100}),1);
  return {...exampleProposal(),strategy:'OPTIONS',assetClass:'OPTION',symbol:'TEST',underlying:'TEST',side:strategy.startsWith('LONG')?'BUY':'SELL',limitPrice:strategy.startsWith('LONG')?1.03:0.97,option:{optionId,type,strike:10,expiration,contracts:1,strategy,maxLoss:0,collateralRequired:0,estimatedPremium:999999}};
}
describe('V2 deterministic foundation',()=>{
  it('timed agent pause is a persisted directive and expires without enabling a disabled sleeve',async()=>{const m=await fixture(),s=m.tradingAgent.create('test','OPERATOR'),p=m.proposals.create(exampleProposal(),'test');await m.tradingAgent.tool(s.id,'test','turn','message','pause_strategy_until',{strategy:'AGGRESSIVE_STOCKS',until:new Date(Date.now()+86400000).toISOString(),reason:'Pause until tomorrow'});expect((await m.proposals.risk(p.id)).checks.find(c=>c.code==='PAUSE_DIRECTIVE')?.ok).toBe(false);m.database.setStrategyEnabled('AGGRESSIVE_STOCKS',false,'test','Other independent pause');m.database.raw.prepare("UPDATE directives SET expires_at=? WHERE type='STRATEGY_PAUSE'").run('2020-01-01T00:00:00Z');m.directives.expireDue();expect(m.database.getStrategy('AGGRESSIVE_STOCKS')?.enabled).toBe(false);});
  it('persistent turn summary records actual offline instruction and no fabricated actions',async()=>{const m=await fixture(),s=m.tradingAgent.create('test');await m.tradingAgent.chat(s.id,'test','Show account performance');const row=m.database.raw.prepare('SELECT summary FROM agent_summaries WHERE session_id=?').get(s.id) as {summary:string};expect(JSON.parse(row.summary)).toMatchObject({userInstruction:'Show account performance',actionIds:[]});});
  it('emergency liquidation prepares owned CLOSE drafts and cannot execute or approve them',async()=>{const m=await fixture();buy(m.ledger,'AGGRESSIVE_STOCKS','TEST',1,10,'emergency-seed');const before=(m.database.raw.prepare('SELECT COUNT(*) AS n FROM orders').get() as {n:number}).n,r=prepareEmergencyCloses(m.proposals,null,'test','Reduce all known owned risk after review');expect(r.ordersPlaced).toBe(0);expect(r.drafts).toHaveLength(1);expect(r.drafts[0]).toMatchObject({positionEffect:'CLOSE',side:'SELL',state:'DRAFT',quantity:1});expect((m.database.raw.prepare('SELECT COUNT(*) AS n FROM orders').get() as {n:number}).n).toBe(before);await expect(m.proposals.execute(r.drafts[0]!.id,'test')).rejects.toThrow('not ready');});
  it('passes isolated self-tests without real broker access',async()=>{expect(await runSelfTests()).toMatchObject({ok:true,simulated:true});});
  it('has exactly the three active sleeves and manual default policies',async()=>{const m=await fixture();expect(m.database.listStrategies().map(s=>s.id)).toEqual(SLEEVES);for(const s of SLEEVES)expect(m.allocation.policy(s).executionPolicy).toBe('MANUAL_APPROVAL');});
  it('allocates thirds of NAV, never buying power, without forced sales',async()=>{const m=await fixture();const before=m.ledger.listPositions();const result=m.allocation.weekly(950);for(const x of result)expect(x.target).toBeCloseTo(950/3,8);expect(m.ledger.listPositions()).toEqual(before);expect(SLEEVES.reduce((n,s)=>n+m.ledger.getCash(s),0)).toBeCloseTo(50000,2);});
  it('normalizes weight changes and conserves total free cash',async()=>{const m=await fixture();m.allocation.setWeight('SAFE_LONG_TERM',.5,'test');const before=SLEEVES.reduce((n,s)=>n+m.ledger.getCash(s),0);m.allocation.weekly(before);expect(SLEEVES.reduce((n,s)=>n+m.allocation.policy(s).targetWeight,0)).toBeCloseTo(1);expect(SLEEVES.reduce((n,s)=>n+m.ledger.getCash(s),0)).toBeCloseTo(before,2);});
  it('rejects incomplete research and illegal lifecycle transitions',async()=>{const m=await fixture(),p=m.proposals.create(exampleProposal(),'test');expect(()=>m.proposals.transition(p.id,'EXECUTION_SENT','test')).toThrow('Illegal');expect(()=>m.proposals.research(p.id,{...research(p.strategy),items:research(p.strategy).items.slice(1)},'test')).toThrow('missing');});
  it('edits invalidate approvals, risk and research, and increment version',async()=>{const m=await fixture(),p=await ready(m);expect(p.state).toBe('READY_TO_EXECUTE');m.proposals.approve(p.id,p.version,'test');const edited=m.proposals.modify(p.id,{...exampleProposal(),quantity:2},'test');expect(edited).toMatchObject({version:2,state:'DRAFT'});expect(m.proposals.detail(p.id)).toMatchObject({approval:null,research:null,preview:null});await expect(m.proposals.execute(p.id,'test')).rejects.toThrow('not ready');});
  it('second risk blocks a newly paused account, without creating an execution',async()=>{const m=await fixture(),p=await ready(m);m.proposals.approve(p.id,1,'test');m.database.setSetting('global_pause',true);await m.proposals.execute(p.id,'test');expect(m.proposals.get(p.id).state).toBe('RISK_REJECTED');expect(m.database.raw.prepare('SELECT * FROM executions_v2').all()).toHaveLength(0);});
  it('stale broker preview cannot execute',async()=>{const m=await fixture(),p=await ready(m);m.proposals.approve(p.id,1,'test');m.database.raw.prepare('UPDATE proposals SET preview_json=? WHERE id=?').run(JSON.stringify({asOf:new Date(Date.now()-120000).toISOString()}),p.id);await m.proposals.execute(p.id,'test');expect(m.proposals.get(p.id).state).toBe('RISK_REJECTED');});
  it('blocks Read Only, maintenance and STOP regardless of manual approval',async()=>{const m=await fixture(),p=await ready(m);m.proposals.approve(p.id,1,'test');m.database.setSetting('operating_mode','READ_ONLY');await expect(m.proposals.execute(p.id,'test')).rejects.toThrow('Read Only');m.database.setSetting('operating_mode','SIMULATION');m.database.setSetting('stopped',true);m.database.setSetting('maintenance_mode',true);const r=await m.proposals.risk(p.id);expect(r.checks.find(c=>c.code==='MAINTENANCE_STOP')?.ok).toBe(false);});
  it('latched 60% emergency kill requires explicit review and reset never resumes',async()=>{const m=await fixture();const before=m.allocation.state('AGGRESSIVE_STOCKS');m.database.raw.prepare('UPDATE strategy_cash SET balance=? WHERE strategy_id=?').run(before.currentEquity*.39,'AGGRESSIVE_STOCKS');expect(m.allocation.state('AGGRESSIVE_STOCKS').killed).toBe(true);expect(()=>m.allocation.reset('AGGRESSIVE_STOCKS','RESET','short','test')).toThrow();m.allocation.reset('AGGRESSIVE_STOCKS','RESET AGGRESSIVE_STOCKS','Explicit weekly review of all loss and capital risks.','test');expect(m.allocation.state('AGGRESSIVE_STOCKS').killed).toBe(false);expect(m.database.getStrategy('AGGRESSIVE_STOCKS')!.enabled).toBe(false);});
  it('normal limit blocks new risk well before emergency kill',async()=>{const m=await fixture();const initial=m.allocation.state('AGGRESSIVE_STOCKS');m.database.raw.prepare('UPDATE strategy_cash SET balance=? WHERE strategy_id=?').run(initial.cash*.85,'AGGRESSIVE_STOCKS');const p=m.proposals.create(exampleProposal(),'test'),r=await m.proposals.risk(p.id);expect(r.checks.find(c=>c.code==='NORMAL_DRAWDOWN')?.ok).toBe(false);expect(m.allocation.state(p.strategy).killed).toBe(false);});
  it('does not trust proposed options premium/maxLoss and books long contracts and close P&L',async()=>{const m=await fixture(),input=option(m),p=await ready(m,input);expect(p.state).toBe('READY_TO_EXECUTE');const r=await m.proposals.risk(p.id);expect(r.facts.maxLoss).toBe(103);const cash=m.ledger.getCash('OPTIONS');m.proposals.approve(p.id,1,'test');await m.proposals.execute(p.id,'test');expect(m.ledger.getCash('OPTIONS')).toBeCloseTo(cash-101);expect(m.allocation.state('OPTIONS').options[0]!.contracts).toBe(1);expect(m.database.raw.prepare("SELECT * FROM trading_reports WHERE kind='OPTIONS_EXPOSURE_CHANGE'").all()).toHaveLength(1);const exit=await ready(m,{...input,side:'SELL',positionEffect:'CLOSE',limitPrice:.97,createdAt:nowIso()});m.proposals.approve(exit.id,1,'test');await m.proposals.execute(exit.id,'test');expect(m.allocation.state('OPTIONS').options).toHaveLength(0);expect(m.ledger.getRealizedPnl('OPTIONS')).toBeCloseTo(-2);});
  it('requires same-sleeve covered-call shares, not SAFE shares',async()=>{const m=await fixture();buy(m.ledger,'SAFE_LONG_TERM','TEST',100,10,'cover-safe');const p=await ready(m,option(m,'COVERED_CALL'));expect(p.state).toBe('RISK_REJECTED');const r=await m.proposals.risk(p.id);expect(r.checks.find(c=>c.code==='SAME_SLEEVE_COVERAGE')?.ok).toBe(false);m.allocation.transferPosition('SAFE_LONG_TERM','OPTIONS','TEST',100,'Operator assigns collateral ownership explicitly.','test');await m.proposals.review(p.id,'test');expect(m.proposals.get(p.id).state).toBe('READY_TO_EXECUTE');m.proposals.approve(p.id,1,'test');await m.proposals.execute(p.id,'test');expect(m.allocation.state('OPTIONS').options[0]!.reserved_shares).toBe(100);expect(()=>m.allocation.transferPosition('OPTIONS','SAFE_LONG_TERM','TEST',1,'Attempt to steal coverage','test')).toThrow('reserved');});
  it('requires full strike cash for a short put and reserves it after a fill',async()=>{const m=await fixture(),p=await ready(m,option(m,'CASH_SECURED_PUT'));const r=await m.proposals.risk(p.id);expect(r.facts.cashRequired).toBe(1000);m.proposals.approve(p.id,1,'test');await m.proposals.execute(p.id,'test');expect(m.allocation.state('OPTIONS').reservedCapital).toBe(1000);});
  it('rejects Level 3/multi-leg and fractional contract schemas',async()=>{const m=await fixture(),input=option(m);expect(proposalSchema.safeParse({...input,quantity:.5}).success).toBe(false);expect(proposalSchema.safeParse({...input,option:{...input.option,strategy:'SPREAD'}}).success).toBe(false);expect(proposalSchema.safeParse({...input,legs:[]}).success).toBe(false);});
  it('unknown placement outcomes reserve capital, pause globally and never replay placement',async()=>{const m=await fixture(),sim=new SimulationTradingBroker(m.database,m.ledger,m.market);let calls=0;const broker:TradingBroker={deterministic:true,account:()=>sim.account(),quote:p=>sim.quote(p),preview:o=>sim.preview(o),cancel:id=>sim.cancel(id),place:async(_o:ExecutableOrder)=>{calls++;throw new Error('Timeout after send');}};const service=new ProposalService(m.database,m.ledger,m.allocation,()=>broker),p=service.create(exampleProposal(),'test');service.research(p.id,research(p.strategy),'test');await service.review(p.id,'test');service.approve(p.id,1,'test');await expect(service.execute(p.id,'test')).rejects.toThrow('Timeout');expect(service.get(p.id).state).toBe('RECONCILIATION_REQUIRED');await service.execute(p.id,'test');expect(calls).toBe(1);expect(m.database.getSetting('global_pause')).toBe(true);expect(m.allocation.state(p.strategy).reservedCapital).toBeGreaterThan(0);});
  it('agent tool modes are enforced server-side and tools are audit logged',async()=>{const m=await fixture(),s=m.tradingAgent.create('test','ADVISOR');expect(AGENT_TOOLS).toHaveLength(25);const result=await m.tradingAgent.tool(s.id,'test','turn','user','pause_strategy',{strategy:'SAFE_LONG_TERM',reason:'Pause request'});expect(result).toHaveProperty('error');expect(m.tradingAgent.actions(s.id,'test')).toHaveLength(1);expect(()=>m.tradingAgent.history(s.id,'another-operator')).toThrow('not found');});
  it('autonomous policy is sleeve-specific and default manual still requires approval',async()=>{const m=await fixture(),p=await ready(m);await expect(m.proposals.execute(p.id,'agent','AUTONOMOUS')).rejects.toThrow('approval');m.allocation.updatePolicy(p.strategy,{...m.allocation.policy(p.strategy),executionPolicy:'AUTONOMOUS_RISK_APPROVED'},'test');await m.proposals.execute(p.id,'agent','AUTONOMOUS');expect(m.proposals.get(p.id).state).toBe('FILLED');expect(m.allocation.policy('SAFE_LONG_TERM').executionPolicy).toBe('MANUAL_APPROVAL');});
  it('persistent mocked Responses tool loop calls app tools and records turns',async()=>{const m=await fixture();let n=0;const agent=new PersistentTradingAgent(m.database,m.proposals,{respond:async()=>({output:n++===0?[{type:'function_call',name:'get_account_state',arguments:'{}',call_id:'c1'}]:[{type:'message',content:[{type:'output_text',text:'Simulation account reviewed.'}]}]})});const s=agent.create('test');const result=await agent.chat(s.id,'test','What is the account state?');expect(result.message).toBe('Simulation account reviewed.');expect(agent.history(s.id,'test')).toHaveLength(2);expect(agent.actions(s.id,'test')).toHaveLength(1);});
  it('holidays skip scheduled reviews and repeated slots are persisted once',async()=>{const m=await fixture();await m.tradingScheduler.tick(new Date('2026-12-25T21:20:00Z'));expect(m.database.raw.prepare('SELECT * FROM trading_reports').all()).toHaveLength(0);const date=new Date('2026-09-18T20:20:00Z');await m.tradingScheduler.tick(date);await m.tradingScheduler.tick(date);expect(m.database.raw.prepare("SELECT * FROM trading_reports WHERE kind='WEEKLY_REPORT'").all()).toHaveLength(1);});
  it('partial fills and duplicate fills preserve pending reservations and attributed shares',async()=>{const m=await fixture(),sim=new SimulationTradingBroker(m.database,m.ledger,m.market);const broker:TradingBroker={deterministic:true,account:()=>sim.account(),quote:p=>sim.quote(p),preview:o=>sim.preview(o),cancel:id=>sim.cancel(id),place:async o=>{const result=await sim.place(o);return {...result,fills:result.fills.map(f=>({...f,quantity:1}))};}};const service=new ProposalService(m.database,m.ledger,m.allocation,()=>broker),p=service.create({...exampleProposal(),quantity:2},'test');service.research(p.id,research(p.strategy),'test');await service.review(p.id,'test');service.approve(p.id,1,'test');await service.execute(p.id,'test');expect(service.get(p.id).state).toBe('PARTIALLY_FILLED');expect(m.allocation.state(p.strategy).reservedCapital).toBe(60);const row=m.database.raw.prepare('SELECT broker_order_id FROM executions_v2 WHERE proposal_id=?').get(p.id) as {broker_order_id:string};const applied=m.database.raw.prepare('SELECT broker_fill_id,price FROM fills LIMIT 1').get() as {broker_fill_id:string;price:number};const fill={id:applied.broker_fill_id,brokerOrderId:row.broker_order_id,quantity:1,price:applied.price,fees:0,executedAt:nowIso()};service.applyFill(p.id,fill);expect(m.ledger.getPosition(p.strategy,p.symbol)?.quantity).toBe(1);expect(m.allocation.state(p.strategy).reservedCapital).toBe(60);service.applyFill(p.id,{...fill,id:'second-partial'});expect(service.get(p.id).state).toBe('FILLED');expect(m.allocation.state(p.strategy).reservedCapital).toBe(0);expect(m.ledger.getPosition(p.strategy,p.symbol)?.quantity).toBe(2);});
  it('unsupported/denied preview never reaches READY',async()=>{const m=await fixture(),sim=new SimulationTradingBroker(m.database,m.ledger,m.market);const broker:TradingBroker={deterministic:true,account:()=>sim.account(),quote:p=>sim.quote(p),preview:async()=>({approved:false,asOf:nowIso(),estimatedCost:0,collateralRequired:0,reason:'Unsupported capability'}),cancel:id=>sim.cancel(id),place:o=>sim.place(o)};const service=new ProposalService(m.database,m.ledger,m.allocation,()=>broker),p=service.create(exampleProposal(),'test');service.research(p.id,research(p.strategy),'test');await service.review(p.id,'test');expect(service.get(p.id).state).toBe('RISK_REJECTED');await expect(service.execute(p.id,'test')).rejects.toThrow('not ready');});
  it('stale quote, depleted buying power, and incomplete broker facts fail closed',async()=>{const m=await fixture(),sim=new SimulationTradingBroker(m.database,m.ledger,m.market);const broker:TradingBroker={deterministic:true,account:async()=>({...await sim.account(),buyingPower:0,complete:false}),quote:async p=>({...await sim.quote(p),asOf:new Date(Date.now()-180000).toISOString()}),preview:o=>sim.preview(o),cancel:id=>sim.cancel(id),place:o=>sim.place(o)};const service=new ProposalService(m.database,m.ledger,m.allocation,()=>broker),p=service.create(exampleProposal(),'test'),r=await service.risk(p.id);expect(r.checks.filter(c=>!c.ok).map(c=>c.code)).toEqual(expect.arrayContaining(['BROKER_HEALTH','QUOTE','CASH_COLLATERAL']));expect((await service.reconcile()).clear).toBe(false);expect(m.database.getSetting('global_pause')).toBe(true);});
  it('external transferred holdings cannot be acknowledged into clean reconciliation',async()=>{const m=await fixture(),sim=new SimulationTradingBroker(m.database,m.ledger,m.market);const broker:TradingBroker={deterministic:true,account:async()=>({...await sim.account(),positions:[{symbol:'TRANSFER',quantity:1,averageCost:10,price:10,assetClass:'EQUITY'}]}),quote:p=>sim.quote(p),preview:o=>sim.preview(o),cancel:id=>sim.cancel(id),place:o=>sim.place(o)};const service=new ProposalService(m.database,m.ledger,m.allocation,()=>broker);expect((await service.reconcile()).mismatches).toContain('Equity ownership mismatch: TRANSFER');expect(m.database.getSetting('reconciliation_clear')).toBe(false);});
  it('emergency kill cannot be bypassed through legacy strategy resume',async()=>{const m=await fixture();const initial=m.allocation.state('SAFE_LONG_TERM');m.database.raw.prepare("UPDATE strategy_cash SET balance=? WHERE strategy_id='SAFE_LONG_TERM'").run(initial.cash*.3);expect(m.allocation.state('SAFE_LONG_TERM').killed).toBe(true);expect(()=>m.database.setStrategyEnabled('SAFE_LONG_TERM',true,'test','Attempt resume')).toThrow('Latched');});
});
