import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,ShieldCheck} from 'lucide-react';
import {api} from '../api';
import type {Dashboard,View} from '../types';
import type {State} from './TradingWorkspace';
import {EquityChart,type Point} from './EquityChart';
import {connectionLabel,type ConnectionData} from './ConnectionGuide';

const names:Record<string,string>={SAFE_LONG_TERM:'Safe',AGGRESSIVE_STOCKS:'Aggressive',OPTIONS:'Options'};
const descriptions:Record<string,string>={SAFE_LONG_TERM:'Long-term stocks and ETFs, with fewer trades.',AGGRESSIVE_STOCKS:'Shorter-term stock opportunities, with more price movement.',OPTIONS:'Option contracts with defined controls for premium and collateral.'};
const money=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-US',{style:'currency',currency:'USD'}):'Not available';
const sign=(n:number)=>n>0?'positive':n<0?'negative':'muted';
const pnlText=(n:number)=>(n>0?'+':'')+money(n);
type Holding={strategy_id:string;symbol:string;quantity:number;average_cost:number;market_price:number};
type Proposal={id:string;strategy:string;symbol:string;thesis:string;invalidation:string;exitPlan:string;state:string;createdAt?:string};
type Data={state:State;connections:ConnectionData;summary:{today:{pnl:number|null};week:{pnl:number|null}};readiness:{checks:Record<string,boolean>};positions:Holding[];proposals:Proposal[];orders:Array<Record<string,unknown>>};

export function AccountExperience({dashboard,section,navigate,openChat}:{dashboard:Dashboard;section:'account'|'strategies'|'positions';navigate:(view:View)=>void;openChat:()=>void}) {
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[period,setPeriod]=useState('1M'),[charts,setCharts]=useState<Record<string,Point[]>>({}),[chartError,setChartError]=useState(''),[chartLoading,setChartLoading]=useState(true),[retry,setRetry]=useState(0);
  const load=useCallback(async()=>{try{
    const [state,connections,summary,readiness,positions,proposals,orders]=await Promise.all([api<State>('/api/v2/state'),api<ConnectionData>('/api/v2/connections'),api<Data['summary']>('/api/v2/performance-summary'),api<Data['readiness']>('/api/v2/production-readiness'),api<Holding[]>('/api/v2/resources/positions'),api<Proposal[]>('/api/v2/proposals'),api<Data['orders']>('/api/v2/resources/orders')]);
    setData({state,connections,summary,readiness,positions,proposals,orders});setError('');
  }catch(e){setError(e instanceof Error?e.message:String(e));}},[]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[load,dashboard]);
  const positionKeys=data?.positions.map(p=>p.strategy_id+':'+p.symbol).join(',')??'';
  useEffect(()=>{let active=true;setChartLoading(true);setChartError('');const keys=['ACCOUNT',...Object.keys(names),...positionKeys.split(',').filter(Boolean)];void Promise.all(keys.map(async key=>{const [strategy,instrument]=key.split(':');const query=new URLSearchParams({period});if(strategy!=='ACCOUNT')query.set('strategy',strategy!);if(instrument)query.set('instrument',instrument);return [key,(await api<{points:Point[]}>('/api/v2/charts?'+query)).points] as const;})).then(entries=>{if(active){setCharts(Object.fromEntries(entries));setChartLoading(false);}}).catch(e=>{if(active){setChartError(e instanceof Error?e.message:String(e));setChartLoading(false);}});return()=>{active=false;};},[period,positionKeys,retry,dashboard]);
  if(!data)return <div className="panel product-card" role="status">{error||'Loading your account…'}{error&&<button onClick={()=>void load()}>Try again</button>}</div>;
  const {state,connections,summary,readiness,positions}=data;
  const account=dashboard.simulated||state.readiness.checks.readOnlyVerification?state.account:null;
  const setupSteps=[{label:'Try a safe simulation',done:!!readiness.checks.simulation,view:'simulation' as View},{label:'Connect Robinhood',done:connections.connectors.some(c=>c.id==='ROBINHOOD'&&['CONNECTED','READ_ONLY'].includes(c.state)),view:'connections' as View},{label:'Verify your read-only account',done:!!readiness.checks.readOnlyReconciliation,view:'connections' as View}];
  const next=setupSteps.find(s=>!s.done);
  const pending=data.proposals.filter(p=>p.state==='READY_TO_EXECUTE').length;
  const chartsFor=(key:string,compact=false)=>chartLoading?<div className="chart-empty" role="status">Loading history…</div>:chartError?<p role="alert">History unavailable. <button onClick={()=>setRetry(n=>n+1)}>Retry charts</button></p>:<EquityChart points={charts[key]??[]} compact={compact} label={(names[key]??key)+' value'}/>;
  const rangePicker=<div className="range-picker" aria-label="Chart time range">{['1D','1W','1M','3M','1Y','ALL'].map(p=><button key={p} aria-pressed={period===p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div>;
  return <div className="product-stack">
    {error&&<div role="alert" className="inline-error">Could not refresh. Values below may be out of date. {error}<button onClick={()=>void load()}>Retry</button></div>}
    {section==='account'&&<>
      <div className="account-welcome"><div><p className="eyebrow">YOUR MONEY, AT A GLANCE</p><h2>{dashboard.simulated?'A place to practice. A plan to connect.':'Your account, in one place.'}</h2><p>Follow your money, understand each strategy, and review what happens next.</p></div><button className="button secondary" onClick={openChat}>Ask the assistant <ArrowRight size={16}/></button></div>
      <div className="account-status"><span><ShieldCheck size={16}/> Real trading disabled</span>{connections.connectors.filter(c=>['ROBINHOOD'].includes(c.id)).map(c=><button key={c.id} onClick={()=>navigate('connections')}>{c.id==='OPENAI'?'OpenAI':'Robinhood'} <b>{connectionLabel(c.state,c.configured)}</b></button>)}</div>
      {next&&<section className="next-step"><div><span className="card-kicker">YOUR NEXT STEP</span><h3>{next.label}</h3><p>{next.view==='simulation'?'Test the whole app with practice money. No brokerage connection is needed.':'Continue setup when you’re ready. Your practice account stays available.'}</p></div><button className="button primary" onClick={()=>navigate(next.view)}>Continue setup <ArrowRight size={16}/></button></section>}
      {(state.stopped||state.reconciliation.length>0||pending>0)&&<div className="attention-row">{state.stopped&&<button onClick={()=>navigate('acceptance')}>Emergency stop is active · Review controls</button>}{state.reconciliation.length>0&&<button onClick={()=>navigate('reconciliation')}>Account differences need review ({state.reconciliation.length})</button>}{pending>0&&<button onClick={()=>navigate('trading')}>{pending} trade {pending===1?'review':'reviews'} waiting</button>}</div>}
      <section className="panel account-hero"><div className="account-hero-heading"><div><p className="card-kicker">{dashboard.simulated?'PRACTICE ACCOUNT VALUE':'LAST VERIFIED ACCOUNT VALUE'}</p><h2>{money(account?.netAccountValue)}</h2><p className={summary.today.pnl===null?'muted':sign(summary.today.pnl)}>{summary.today.pnl===null?'Today’s return is building':pnlText(summary.today.pnl)+' today'} <span className="muted">· recorded since first observation</span></p></div>{rangePicker}</div>{chartsFor('ACCOUNT')}<div className="account-facts"><div><span>Buying power</span><strong>{money(account?.buyingPower)}</strong></div><div><span>Cash</span><strong>{money(account?.cash)}</strong></div><div><span>This week</span><strong className={summary.week.pnl===null?'muted':sign(summary.week.pnl)}>{summary.week.pnl===null?'History building':pnlText(summary.week.pnl)}</strong></div></div><p className="chart-note">Chart: money attributed to your strategies. Cash transfers can change its shape. {account?'Account last synced '+new Date(account.asOf).toLocaleString()+'.':'Connect and sync to see a verified account balance.'}</p></section>
    </>}
    {section!=='positions'&&<><div className="section-heading"><div><h2>Your strategies</h2><p className="muted">Separate approaches. One account. Shared safety controls.</p></div>{section==='strategies'?rangePicker:<button onClick={()=>navigate('strategies')}>Explore strategies <ArrowRight size={16}/></button>}</div><div className="strategy-grid">{state.sleeves.map(s=>{const pnl=s.realizedPnL+s.unrealizedPnL;return <article className="panel strategy-card" key={s.strategy}><div className="strategy-card-top"><span className={'strategy-symbol '+s.strategy}>{names[s.strategy]?.slice(0,1)}</span><span className="status-text">{s.killed?'Stopped by risk':!s.enabled?'Paused':state.globalPause?'Paused globally':'Monitoring'}</span></div><h3>{names[s.strategy]}</h3><p className="strategy-description">{descriptions[s.strategy]}</p><h2>{money(s.currentEquity)}</h2><p className={sign(pnl)}>{pnlText(pnl)} <span className="muted">total gain / loss</span></p>{chartsFor(s.strategy,true)}<small className="muted">Equity history · includes capital allocations</small><dl className="plain-facts"><div><dt>Assigned target</dt><dd>{money(s.target)}</dd></div><div><dt>Invested value</dt><dd>{money(s.currentEquity-s.cash)}</dd></div><div><dt>Available</dt><dd>{money(s.availableCapital)}</dd></div><div><dt>Open positions</dt><dd>{s.positions.length+s.options.length}</dd></div><div><dt>Trade approval</dt><dd>{s.policy.executionPolicy==='MANUAL_APPROVAL'?'You approve':'Automatic, within limits'}</dd></div></dl>{s.killReason&&<p className="negative">{s.killReason}</p>}{section==='strategies'&&<><p className="muted">{s.strategy==='SAFE_LONG_TERM'?'Lower turnover does not mean risk-free.':s.strategy==='OPTIONS'?'Options can lose their full premium; short contracts carry assignment risk.':'Short-term prices can move quickly; losses are possible.'}</p><details><summary>Capital, risk & activity</summary><dl className="plain-facts"><div><dt>Realized gain / loss</dt><dd>{pnlText(s.realizedPnL)}</dd></div><div><dt>Unrealized gain / loss</dt><dd>{pnlText(s.unrealizedPnL)}</dd></div><div><dt>Capital at risk</dt><dd>{money(s.capitalAtRisk)}</dd></div><div><dt>Reserved for orders</dt><dd>{money(s.reservedCapital)}</dd></div><div><dt>Fall from peak</dt><dd>{s.drawdown.toFixed(2)}%</dd></div></dl><button onClick={()=>navigate('portfolio')}>View holdings</button><button onClick={()=>navigate('strategy-settings')}>Manage strategy settings</button></details></>}<button onClick={()=>navigate('risk-configuration')}>Review risk limits</button></article>;})}</div></>}
    {(section==='positions'||section==='account')&&<section className="panel product-card"><div className="section-heading"><div><h2>Your holdings</h2><p className="muted">Open a holding to see cost, performance, and recorded trade reasoning.</p></div>{section==='positions'?rangePicker:<button onClick={()=>navigate('portfolio')}>All holdings <ArrowRight size={16}/></button>}</div>{!positions.length&&<div className="useful-empty"><CheckCircle2/><h3>No stocks held right now.</h3><p>This is normal for a new or all-cash account. Start with a simulation, or sync Robinhood to see verified holdings.</p><button onClick={()=>navigate(dashboard.simulated?'simulation':'connections')}>{dashboard.simulated?'Try simulation':'Connect and sync'}</button></div>}{positions.map(p=>{const gain=p.quantity*(p.market_price-p.average_cost),related=data.proposals.filter(r=>r.symbol===p.symbol&&r.strategy===p.strategy_id),orders=data.orders.filter(o=>o.symbol===p.symbol&&o.strategy_id===p.strategy_id);return <details className="holding" key={p.strategy_id+':'+p.symbol}><summary><span><strong>{p.symbol}</strong><small>{names[p.strategy_id]} · {p.quantity} shares</small></span><span className="holding-spark">{chartsFor(p.strategy_id+':'+p.symbol,true)}</span><span><strong>{money(p.quantity*p.market_price)}</strong><small className={sign(gain)}>{pnlText(gain)} unrealized</small></span></summary><div className="holding-detail"><dl className="plain-facts"><div><dt>Average cost / share</dt><dd>{money(p.average_cost)}</dd></div><div><dt>Last recorded price</dt><dd>{money(p.market_price)}</dd></div><div><dt>Cost basis</dt><dd>{money(p.quantity*p.average_cost)}</dd></div></dl>{related.length?related.map(r=><article key={r.id}><h4>Recorded thesis · {r.state.replaceAll('_',' ').toLowerCase()}</h4><p>{r.thesis}</p><p><b>Risk / invalidation:</b> {r.invalidation}</p><p><b>Exit plan:</b> {r.exitPlan}</p></article>):<p>No entry thesis was recorded for this holding. Ask the assistant to explain the available records.</p>}<h4>Recent orders</h4>{orders.length?orders.slice(0,5).map((o,i)=><p key={i}>{String(o.side)} · {String(o.quantity)} shares · {String(o.status).toLowerCase()}</p>):<p>No linked orders or stops are recorded.</p>}<button onClick={openChat}>Ask about this holding</button></div></details>;})}<button className="button secondary" onClick={()=>navigate('options-telemetry')}>View option contracts <ArrowRight size={16}/></button></section>}
    {section==='account'&&<details className="panel product-card"><summary>Setup progress · {setupSteps.filter(s=>s.done).length} of 4 complete</summary><div className="setup-checklist">{setupSteps.map((s,i)=><button key={s.label} onClick={()=>navigate(s.view)}><span>{s.done?'✓':i+1}</span><b>{s.label}</b><small>{s.done?'Complete':'Continue'}</small></button>)}</div><button onClick={()=>navigate('acceptance')}>Review Pi and production checks</button></details>}
  </div>;
}
