import {useCallback,useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,ChevronRight,MessageSquareText} from 'lucide-react';
import {api} from '../api';
import type {Dashboard,View} from '../types';
import type {State} from './TradingWorkspace';
import {EquityChart,type Point} from './EquityChart';
import {connectionLabel,type ConnectionData} from './ConnectionGuide';

const names:Record<string,string>={SAFE_LONG_TERM:'Safe',AGGRESSIVE_STOCKS:'Aggressive',OPTIONS:'Options'};
const descriptions:Record<string,string>={SAFE_LONG_TERM:'Long-term stocks and ETFs, with fewer trades.',AGGRESSIVE_STOCKS:'Shorter-term stock opportunities, with more price movement.',OPTIONS:'Option contracts with defined controls for premium and collateral.'};
const money=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-US',{style:'currency',currency:'USD'}):'Not available';
const sign=(n:number)=>n>0?'positive':n<0?'negative':'muted';
const pnlText=(n:number)=>(n>0?'+':'')+money(n);
type Holding={strategy_id:string;symbol:string;quantity:number;average_cost:number;market_price:number};
type Proposal={id:string;strategy:string;symbol:string;thesis:string;invalidation:string;exitPlan:string;state:string;createdAt?:string};
type Data={state:State;connections:ConnectionData;summary:{today:{pnl:number|null};week:{pnl:number|null}};readiness:{checks:Record<string,boolean>};positions:Holding[];proposals:Proposal[];orders:Array<Record<string,unknown>>};

export function AccountExperience({dashboard,section,navigate,openChat}:{dashboard:Dashboard;section:'account'|'strategies'|'positions';navigate:(view:View)=>void;openChat:(prompt?:string)=>void}) {
  const [selected,setSelected]=useState<string|null>(null);
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[period,setPeriod]=useState('1M'),[charts,setCharts]=useState<Record<string,Point[]>>({}),[chartError,setChartError]=useState(''),[chartLoading,setChartLoading]=useState(true),[retry,setRetry]=useState(0);
  const load=useCallback(async()=>{try{
    const [state,connections,summary,readiness,positions,proposals,orders]=await Promise.all([api<State>('/api/v2/state'),api<ConnectionData>('/api/v2/connections'),api<Data['summary']>('/api/v2/performance-summary'),api<Data['readiness']>('/api/v2/production-readiness'),api<Holding[]>('/api/v2/resources/positions'),api<Proposal[]>('/api/v2/proposals'),api<Data['orders']>('/api/v2/resources/orders')]);
    setData({state,connections,summary,readiness,positions,proposals,orders});setError('');
  }catch(e){setError(e instanceof Error?e.message:String(e));}},[]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[load,dashboard]);
  const positionKeys=data?.positions.map(p=>p.strategy_id+':'+p.symbol).join(',')??'';
  useEffect(()=>{let active=true;setChartLoading(true);setChartError('');const keys=['ACCOUNT',...Object.keys(names),...positionKeys.split(',').filter(Boolean)];void Promise.all(keys.map(async key=>{const [strategy,instrument]=key.split(':');const query=new URLSearchParams({period});if(strategy!=='ACCOUNT')query.set('strategy',strategy!);if(instrument)query.set('instrument',instrument);return [key,(await api<{points:Point[]}>('/api/v2/charts?'+query)).points] as const;})).then(entries=>{if(active){setCharts(Object.fromEntries(entries));setChartLoading(false);}}).catch(e=>{if(active){setChartError(e instanceof Error?e.message:String(e));setChartLoading(false);}});return()=>{active=false;};},[period,positionKeys,retry,dashboard]);
  if(!data)return <div className="panel product-card" role="status">{error||'Loading your account…'}{error&&<button onClick={()=>void load()}>Try again</button>}</div>;
  const {state,connections,summary,readiness}=data;
  const account=dashboard.simulated||state.readiness.checks.readOnlyVerification?state.account:null;
  const reconciled=dashboard.simulated||state.reconciliation.length===0;
  const positions:Holding[]=!dashboard.simulated&&account?.positions?account.positions.map(p=>({strategy_id:reconciled?(data.positions.find(local=>local.symbol===p.symbol)?.strategy_id??'UNASSIGNED'):'UNASSIGNED',symbol:p.symbol,quantity:p.quantity,average_cost:p.averageCost,market_price:p.price})):data.positions;
  const setupSteps=[{label:'Try a safe simulation',done:!!readiness.checks.simulation,view:'simulation' as View},{label:'Connect Robinhood',done:connections.connectors.some(c=>c.id==='ROBINHOOD'&&['CONNECTED','READ_ONLY'].includes(c.state)),view:'connections' as View},{label:'Verify your read-only account',done:!!readiness.checks.readOnlyReconciliation,view:'connections' as View}];
  const next=setupSteps.find(s=>!s.done);
  const selectDetail=(key:string|null)=>{setSelected(key);window.scrollTo({top:0,behavior:'instant'});};
  const pending=data.proposals.filter(p=>p.state==='READY_TO_EXECUTE').length;
  const chartsFor=(key:string,compact=false)=>!reconciled?<p className="muted">Strategy history awaits account reconciliation.</p>:chartLoading?<div className="chart-empty" role="status">Loading history…</div>:chartError?<p role="alert">History unavailable. <button onClick={()=>setRetry(n=>n+1)}>Retry charts</button></p>:<EquityChart points={charts[key]??[]} compact={compact} label={(names[key]??key)+' value'}/>;
  const rangePicker=<div className="range-picker" aria-label="Chart time range">{['1D','1W','1M','3M','1Y','ALL'].map(p=><button key={p} aria-pressed={period===p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div>;
  const holdingDetail=positions.find(p=>'holding:'+p.strategy_id+':'+p.symbol===selected);
  const sleeveDetail=state.sleeves.find(s=>'strategy:'+s.strategy===selected);
  const holdingRows=(limit?:number)=><div className="holding-list">{positions.slice(0,limit).map(p=>{const gain=p.quantity*(p.market_price-p.average_cost);return <button className="holding-row" key={p.strategy_id+':'+p.symbol} onClick={()=>selectDetail('holding:'+p.strategy_id+':'+p.symbol)}><span className="holding-avatar">{p.symbol.slice(0,2)}</span><span className="holding-name"><strong>{p.symbol}</strong><small>{p.quantity} {p.quantity===1?'share':'shares'} · {names[p.strategy_id]??'Unassigned'}</small></span><span className="holding-value"><strong>{money(p.quantity*p.market_price)}</strong><small className={sign(gain)}>{pnlText(gain)}</small></span><ChevronRight size={16}/></button>;})}</div>;
  const strategyRows=<div className="strategy-list">{state.sleeves.map(s=><button className="strategy-summary" key={s.strategy} onClick={()=>selectDetail('strategy:'+s.strategy)}><span className={'strategy-symbol '+s.strategy}>{names[s.strategy]?.slice(0,1)}</span><span><strong>{names[s.strategy]}</strong><small>{s.killed?'Stopped by risk':!s.enabled||state.globalPause?'Paused':'Monitoring'} · {s.policy.executionPolicy==='MANUAL_APPROVAL'?'You approve trades':'Automatic within limits'}</small></span><span className="strategy-summary-value">{reconciled?money(s.currentEquity):'Unverified'}</span><ChevronRight size={16}/></button>)}</div>;
  const attention=state.stopped?{title:'Emergency stop is active',body:'New autonomous orders are stopped. Review recovery controls when you are ready.',view:'acceptance' as View,action:'Review stop'}:state.reconciliation.length?{title:'Your account needs a review',body:`${state.reconciliation.length} account differences need reconciliation. Strategy balances remain unverified.`,view:'reconciliation' as View,action:'Review differences'}:pending?{title:`${pending} trade ${pending===1?'proposal is':'proposals are'} ready`,body:'Review the reasoning and risk checks before making a decision.',view:'trading' as View,action:'Review proposals'}:next?{title:next.label,body:'Complete the next step to finish setting up your workspace.',view:next.view,action:'Continue setup'}:null;
  return <div className={'product-stack account-experience '+(selected?'detail-mode':'')}>
    {error&&<div role="alert" className="inline-error">Could not refresh. Values may be out of date. {error}<button onClick={()=>void load()}>Retry</button></div>}
    {selected&&<button className="detail-back" onClick={()=>selectDetail(null)}><ArrowLeft size={17}/> Back to {section==='positions'?'holdings':section==='strategies'?'strategies':'overview'}</button>}
    {holdingDetail&&(()=>{const p=holdingDetail,gain=p.quantity*(p.market_price-p.average_cost),related=data.proposals.filter(r=>r.symbol===p.symbol&&r.strategy===p.strategy_id),orders=data.orders.filter(o=>o.symbol===p.symbol&&o.strategy_id===p.strategy_id);return <div className="detail-layout"><section className="panel account-hero"><p className="card-kicker">{names[p.strategy_id]??'AWAITING STRATEGY ASSIGNMENT'}</p><h2 className="detail-title">{p.symbol}</h2><div className="detail-balance">{money(p.quantity*p.market_price)}</div><p className={sign(gain)}>{pnlText(gain)} unrealized gain / loss</p>{rangePicker}{chartsFor(p.strategy_id+':'+p.symbol)}<dl className="plain-facts"><div><dt>Shares</dt><dd>{p.quantity}</dd></div><div><dt>Average cost / share</dt><dd>{money(p.average_cost)}</dd></div><div><dt>Last recorded price</dt><dd>{money(p.market_price)}</dd></div><div><dt>Cost basis</dt><dd>{money(p.quantity*p.average_cost)}</dd></div></dl><button className="button primary" onClick={()=>openChat(`Analyze my ${p.symbol} position`)}>Analyze with Codex <ArrowRight size={16}/></button></section><aside className="detail-support"><section className="panel product-card"><h3>Why this holding?</h3>{related.length?related.map(r=><article key={r.id}><p>{r.thesis}</p><details><summary>Risk, exit plan & review status</summary><p>{r.invalidation}</p><p>{r.exitPlan}</p><small>{r.state.replaceAll('_',' ').toLowerCase()}</small></details></article>):<p className="muted">No entry thesis is recorded. Codex can review the available account records.</p>}</section><details className="panel product-card"><summary>Recent orders ({orders.length})</summary>{orders.length?orders.slice(0,5).map((o,i)=><p key={i}>{String(o.side)} · {String(o.quantity)} shares · {String(o.status).toLowerCase()}</p>):<p>No linked orders or stops recorded.</p>}</details></aside></div>;})()}
    {sleeveDetail&&(()=>{const s=sleeveDetail,pnl=s.realizedPnL+s.unrealizedPnL;return <div className="detail-layout"><section className="panel account-hero"><div className="section-heading"><span className={'strategy-symbol '+s.strategy}>{names[s.strategy]?.slice(0,1)}</span><span className="status-text">{s.killed?'Stopped by risk':!s.enabled||state.globalPause?'Paused':'Monitoring'}</span></div><h2 className="detail-title">{names[s.strategy]}</h2><p className="muted">{descriptions[s.strategy]}</p><div className="detail-balance">{reconciled?money(s.currentEquity):'Awaiting verification'}</div><p className={reconciled?sign(pnl):'muted'}>{reconciled?pnlText(pnl)+' total gain / loss':'Account reconciliation is needed before strategy values can be shown.'}</p>{rangePicker}{chartsFor(s.strategy)}<dl className="plain-facts"><div><dt>Assigned target</dt><dd>{money(reconciled?s.target:null)}</dd></div><div><dt>Invested value</dt><dd>{money(reconciled?s.currentEquity-s.cash:null)}</dd></div><div><dt>Available capital</dt><dd>{money(reconciled?s.availableCapital:null)}</dd></div><div><dt>Open positions</dt><dd>{reconciled?s.positions.length+s.options.length:'Unverified'}</dd></div><div><dt>Trade approval</dt><dd>{s.policy.executionPolicy==='MANUAL_APPROVAL'?'You approve each trade':'Automatic within limits'}</dd></div></dl>{s.killReason&&<p className="negative">{s.killReason}</p>}<button className="button primary" onClick={()=>openChat(`Review my ${names[s.strategy]} strategy`)}>Review with Codex <ArrowRight size={16}/></button></section><aside className="detail-support"><section className="panel product-card"><h3>Strategy controls</h3><p className="muted">{s.strategy==='SAFE_LONG_TERM'?'Lower turnover does not mean risk-free.':s.strategy==='OPTIONS'?'Options can lose their full premium; short contracts carry assignment risk.':'Short-term prices can move quickly; losses are possible.'}</p><button onClick={()=>navigate('risk-configuration')}>Risk limits</button><button onClick={()=>navigate('strategy-settings')}>Strategy settings</button><button onClick={()=>navigate('portfolio')}>Holdings</button></section><details className="panel product-card"><summary>Capital & performance details</summary><dl className="plain-facts">{[['Realized gain / loss',s.realizedPnL],['Unrealized gain / loss',s.unrealizedPnL],['Capital at risk',s.capitalAtRisk],['Reserved for orders',s.reservedCapital]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(reconciled?Number(value):null)}</dd></div>)}<div><dt>Fall from peak</dt><dd>{reconciled?s.drawdown.toFixed(2)+'%':'Unverified'}</dd></div></dl></details></aside></div>;})()}
    {!selected&&section==='account'&&<>
      <div className="overview-top"><section className="panel account-hero"><div className="account-hero-heading"><div><p className="card-kicker">{dashboard.simulated?'PRACTICE ACCOUNT':'LAST VERIFIED ACCOUNT VALUE'}</p><h2>{money(account?.netAccountValue)}</h2><p className={!reconciled||summary.today.pnl===null?'muted':sign(summary.today.pnl)}>{!reconciled||summary.today.pnl===null?'Today’s return is not yet available':pnlText(summary.today.pnl)+' today'}</p></div><span className="account-mode">{dashboard.mode==='READ_ONLY'?'Read only':dashboard.simulated?'Simulated funds':'Live account'}</span></div>{rangePicker}{chartsFor('ACCOUNT')}<div className="account-facts"><div><span>Buying power</span><strong>{money(account?.buyingPower)}</strong></div><div><span>Cash</span><strong>{money(account?.cash)}</strong></div><div><span>This week</span><strong className={!reconciled||summary.week.pnl===null?'muted':sign(summary.week.pnl)}>{!reconciled||summary.week.pnl===null?'—':pnlText(summary.week.pnl)}</strong></div></div><details className="chart-provenance"><summary>About these values</summary><p>Chart shows money attributed to strategies. Cash transfers can change its shape. Returns cover recorded observations only.</p><p>{account?'Account last synced '+new Date(account.asOf).toLocaleString()+'.':'Connect and sync to see a verified account balance.'}</p></details></section><aside className="overview-companion">{attention?<section className="next-step"><span className="card-kicker">NEEDS ATTENTION</span><h3>{attention.title}</h3><p>{attention.body}</p><button className="button primary" onClick={()=>navigate(attention.view)}>{attention.action}<ArrowRight size={16}/></button>{pending>0&&attention.view!=='trading'&&<button className="text-link" onClick={()=>navigate('trading')}>{pending} trade reviews waiting</button>}</section>:<section className="next-step quiet"><CheckCircle2 size={22}/><h3>You’re up to date</h3><p>No setup steps or trade reviews are waiting.</p></section>}<button className="codex-invitation" onClick={()=>openChat('Review my account')}><MessageSquareText size={22}/><span><strong>Make sense of your account</strong><small>Ask Codex in plain English</small></span><ArrowRight size={18}/></button><button className="connection-compact" onClick={()=>navigate('connections')}><span>Robinhood</span><strong>{connections.connectors.find(c=>c.id==='ROBINHOOD')?connectionLabel(connections.connectors.find(c=>c.id==='ROBINHOOD')!.state,connections.connectors.find(c=>c.id==='ROBINHOOD')!.configured):'Not connected'}</strong><ChevronRight size={14}/></button></aside></div>
      <div className="overview-bottom"><section className="panel overview-holdings"><div className="section-heading"><h2>Holdings</h2><button className="text-link" onClick={()=>navigate('portfolio')}>View all <ArrowRight size={15}/></button></div>{positions.length?holdingRows(4):<p className="muted">{dashboard.simulated||state.account?'No stocks held right now.':'Holdings await broker verification. Review account differences.'}</p>}</section><section className="panel overview-strategies"><div className="section-heading"><h2>Strategies</h2><button className="text-link" onClick={()=>navigate('strategies')}>View all <ArrowRight size={15}/></button></div>{strategyRows}</section></div>
      <details className="panel product-card setup-progress"><summary>Setup progress · {setupSteps.filter(s=>s.done).length} of {setupSteps.length} complete</summary><div className="setup-checklist">{setupSteps.map((s,i)=><button key={s.label} onClick={()=>navigate(s.view)}><span>{s.done?'✓':i+1}</span><b>{s.label}</b><small>{s.done?'Complete':'Continue'}</small></button>)}</div><button onClick={()=>navigate('acceptance')}>Device & readiness checks</button></details>
    </>}
    {!selected&&section==='strategies'&&<><div className="page-intro"><h2>Three approaches. One account.</h2><p>Choose a strategy to see its performance, holdings, and controls.</p></div>{!reconciled&&<p className="safety-note">Strategy values are hidden until account differences are resolved. <button className="text-link" onClick={()=>navigate('reconciliation')}>Review differences</button></p>}<div className="strategy-browse">{state.sleeves.map(s=><button className="panel strategy-tile" key={s.strategy} onClick={()=>selectDetail('strategy:'+s.strategy)}><span className={'strategy-symbol '+s.strategy}>{names[s.strategy]?.slice(0,1)}</span><span className="status-text">{s.killed?'Stopped by risk':!s.enabled||state.globalPause?'Paused':'Monitoring'}</span><h3>{names[s.strategy]}</h3><p>{descriptions[s.strategy]}</p><strong className="strategy-tile-value">{reconciled?money(s.currentEquity):'Awaiting verification'}</strong>{reconciled&&chartsFor(s.strategy,true)}<span className="strategy-tile-footer">View strategy <ArrowRight size={17}/></span></button>)}</div></>}
    {!selected&&section==='positions'&&<><div className="section-heading"><div><h2>Your holdings</h2><p className="muted">Stocks in your last verified account snapshot.</p></div><button className="button secondary" onClick={()=>navigate('options-telemetry')}>Option contracts <ArrowRight size={16}/></button></div><section className="panel holdings-page">{positions.length?holdingRows():<div className="useful-empty"><CheckCircle2/><h3>{dashboard.simulated||state.account?'No stocks held right now.':'Holdings await broker verification.'}</h3><p>Sync your account or explore with practice money.</p><button onClick={()=>navigate(dashboard.simulated?'simulation':'connections')}>{dashboard.simulated?'Try simulation':'Connect and sync'}</button></div>}</section>{!reconciled&&<p className="muted">Unassigned holdings need account reconciliation before they can belong to a strategy. <button className="text-link" onClick={()=>navigate('reconciliation')}>Review account differences</button></p>}</>}
  </div>;
}
