import {useCallback,useEffect,useRef,useState} from 'react';
import {api,post} from '../api';
import {SensitiveActionAuth} from './SensitiveActionAuth';

type Fields=Record<string,unknown>;
type Cadence={enabled:boolean;reviewMinutes:number;cooldownMinutes:number;monitorSeconds:number;activeOrderPollSeconds:number;materialMovePercent:number;nearExpiryDays:number};
type Sleeve={strategy:string;enabled:boolean;autonomous:boolean;killed:boolean;allocation:number;activeTasks:Fields[]|number;activeOrders:Fields[]|number;realizedPnL?:number|null;unrealizedPnL?:number|null;riskStatus?:string;killReason?:string|null;behavior?:Fields;nextAnalysisAt?:string|null};
type SupervisorSleeve={status:string;reason:string;nextAnalysisAt:string|null;activeTaskId:string|null;lastTaskStatus:string|null};
type AutonomyState={mode:string;authorized:boolean;ready:boolean;checks:Record<string,boolean>;supervisor:{config:Record<string,Cadence>;state:{sleeves?:Record<string,SupervisorSleeve>;lastMonitorAt?:string;lastError?:string|null}};sleeves:Sleeve[];activity?:Array<{at:string;kind:string;message:string;strategy?:string}>};
const names:Record<string,string>={SAFE_LONG_TERM:'SAFE',AGGRESSIVE_STOCKS:'AGGRESSIVE',OPTIONS:'OPTIONS'};
const gateLabels:Record<string,string>={calendarVerified:'Verified exchange calendar',correctAccount:'Correct Agentic account',freshAccount:'Fresh account state',cleanReconciliation:'Acceptable reconciliation',reviewedOpening:'Opening balances commissioned',reviewedOwnership:'Holdings and ownership reviewed',robinhoodAvailable:'Robinhood connected',brokerReviewVerified:'Official broker preview verified',executionCapabilities:'Execution and cancellation available',deterministicRiskHealthy:'Risk safety checks passed',emergencyStopHealthy:'Emergency STOP healthy',noUnknownOrders:'No unresolved order outcomes',pauseReleased:'Global pause released',stopReleased:'STOP released',maintenanceOff:'Maintenance off',manualLiveEnabled:'Manual Live enabled',codexAvailable:'Codex worker available'};
const human=(s:string)=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const money=(n:number|null|undefined)=>typeof n==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n):'Unavailable';
const when=(value:unknown)=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString(): 'Waiting for schedule';
const count=(value:Fields[]|number)=>typeof value==='number'?value:value.length;
function Rules({value}:{value:Fields}){return <dl>{Object.entries(value).map(([key,v])=><div key={key}><dt>{human(key)}</dt><dd>{Array.isArray(v)?v.join(', ')||'None':v!==null&&typeof v==='object'?<Rules value={v as Fields}/>:typeof v==='boolean'?v?'Yes':'No':String(v??'Unavailable')}</dd></div>)}</dl>;}
const cadenceFields:Array<{key:Exclude<keyof Cadence,'enabled'>;label:string;min:number;max:number;step:number}>=[{key:'reviewMinutes',label:'Routine analysis interval (minutes)',min:5,max:10080,step:1},{key:'cooldownMinutes',label:'Minimum gap between Codex calls (minutes)',min:2,max:1440,step:1},{key:'monitorSeconds',label:'Deterministic monitoring interval (seconds)',min:15,max:3600,step:1},{key:'activeOrderPollSeconds',label:'Active order polling (seconds)',min:15,max:300,step:1},{key:'materialMovePercent',label:'Material price move (%)',min:0.1,max:100,step:0.1},{key:'nearExpiryDays',label:'Options expiry watch (days)',min:0,max:30,step:1}];
function CadenceEditor({strategy,value,busy,save}:{strategy:string;value:Cadence;busy:boolean;save:(config:Cadence)=>Promise<void>}){
  const [draft,setDraft]=useState(value);
  const invalid=cadenceFields.some(f=>!Number.isFinite(draft[f.key])||draft[f.key]<f.min||draft[f.key]>f.max)||draft.cooldownMinutes>draft.reviewMinutes;
  return <details><summary>Analysis and monitoring frequency</summary><p>Deterministic checks continue between Codex calls. Material events can trigger analysis after the cooldown. Trading analysis runs only during a verified market session.</p><form className="terminal-stack" onSubmit={e=>{e.preventDefault();if(!invalid)void save(draft);}}>{cadenceFields.filter(f=>strategy==='OPTIONS'||f.key!=='nearExpiryDays').map(f=><label className="field" key={f.key}><span>{f.label}</span><input type="number" required min={f.min} max={f.max} step={f.step} value={draft[f.key]} onChange={e=>setDraft({...draft,[f.key]:Number(e.target.value)})}/></label>)}{draft.cooldownMinutes>draft.reviewMinutes&&<p role="alert">The minimum gap must not exceed the routine interval.</p>}<button className="button secondary" disabled={busy||invalid}>Save {names[strategy]??strategy} frequency</button></form></details>;
}

export function AutonomyPanel({notify}:{notify:(message:string,tone?:string)=>void}){
  const [data,setData]=useState<AutonomyState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(''),[review,setReview]=useState('');
  const mounted=useRef(true);
  const load=useCallback(async()=>{try{const next=await api<AutonomyState>('/api/v2/autonomy');if(mounted.current){setData(next);setError('');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:String(e));}},[]);
  useEffect(()=>{mounted.current=true;void load();const timer=window.setInterval(()=>void load(),15000);return()=>{mounted.current=false;clearInterval(timer);};},[load]);
  const action=async(path:string,body:unknown,message:string)=>{setBusy(true);try{await post(path,body);await load();notify(message);}catch(e){notify(e instanceof Error?e.message:String(e),'danger');await load();}finally{setBusy(false);}};
  const on=data?.authorized&&data.mode==='AUTONOMOUS_LIVE';
  const blocked=Object.entries(data?.checks??{}).filter(([,passed])=>!passed);
  return <section className="panel product-card terminal-panel" aria-labelledby="autonomy-heading">
    <header className="panel-heading"><div><p className="eyebrow">PRODUCTION CONTROL</p><h2 id="autonomy-heading">Autonomous Live</h2></div><strong role="status">{on?'ON':data?.authorized?'AUTHORIZED · BLOCKED':'OFF'}</strong></header>
    <p>When enabled, qualifying trades proceed through current research, deterministic risk, fresh reconciliation and Robinhood preview without per-trade approval. The application enforces all limits and STOP independently of Codex.</p>
    {error&&<p className="form-error" role="alert">Autonomy status unavailable: {error}. <button className="button secondary" onClick={()=>void load()}>Retry</button></p>}
    <div className="v2-actions"><button className="button secondary" disabled={busy||!data?.authorized} onClick={()=>void action('/api/v2/autonomy',{enabled:false},'Autonomous Live is off. New autonomous submissions are blocked.')}>Turn Autonomous Live OFF</button><button className="button secondary" disabled={busy} onClick={()=>void load()}>Refresh status</button></div>
    {!data&&!error&&<p>Loading autonomous controls…</p>}
    {data&&<>
      <p className="safety-note">{on?'Autonomous authorization is active. Normal restarts retain it; critical faults revoke it.':data.ready?'Runtime checks pass. Autonomous trading still requires your deliberate activation.':'Autonomy is blocked until the required checks pass.'}</p>
      <details open={!data.ready}><summary>Readiness · {blocked.length?`${blocked.length} checks need attention`:'all checks passed'}</summary><div className="assertion-list">{Object.entries(data.checks).map(([key,passed])=><div key={key}><b className="muted">{passed?'PASS':'NEEDED'}</b><span>{gateLabels[key]??human(key)}</span></div>)}</div></details>
      {!on&&<div className="terminal-stack"><SensitiveActionAuth notify={notify}/><label className="field"><span>Activation review</span><textarea rows={3} placeholder="Confirm the account, sleeve allocations and risk settings you reviewed (20+ characters)." value={review} onChange={e=>setReview(e.target.value)}/></label><label className="field"><span>Type ENABLE AUTONOMOUS LIVE</span><input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="button primary" disabled={busy||!data.ready||confirmation!=='ENABLE AUTONOMOUS LIVE'||review.trim().length<20} onClick={()=>void action('/api/v2/autonomy',{enabled:true,confirmation,review},'Autonomous Live enabled. Qualifying trades no longer require per-trade approval.')}>Turn Autonomous Live ON</button></div>}
      <div className="v2-sleeves" style={{marginTop:24}}>{data.sleeves.map(s=>{const monitor=data.supervisor.state.sleeves?.[s.strategy];const active=on&&s.autonomous&&s.enabled&&!s.killed;const status=s.killed||monitor?.status==='BLOCKED'?'Blocked':active?'Autonomous':s.autonomous&&s.enabled?'Blocked':'Paused';return <article className="panel product-card" key={s.strategy}>
        <div className="section-heading"><h3>{names[s.strategy]??s.strategy}</h3><strong>{status}</strong></div>
        <dl><div><dt>Allocation</dt><dd>{money(s.allocation)}</dd></div><div><dt>Realized P&L</dt><dd className={typeof s.realizedPnL==='number'?(s.realizedPnL<0?'negative':'positive'):''}>{money(s.realizedPnL)}</dd></div><div><dt>Unrealized P&L</dt><dd className={typeof s.unrealizedPnL==='number'?(s.unrealizedPnL<0?'negative':'positive'):''}>{money(s.unrealizedPnL)}</dd></div><div><dt>Active Codex tasks</dt><dd>{count(s.activeTasks)}</dd></div><div><dt>Active broker orders</dt><dd>{count(s.activeOrders)}</dd></div></dl>
        <p><small>Next analysis: {when(s.nextAnalysisAt??monitor?.nextAnalysisAt)}</small></p><p><small>Risk: {s.killReason??s.riskStatus??(s.killed?'Kill switch latched':!data.ready?'Runtime checks required':'Deterministic limits enforced')}</small></p>{monitor?.reason&&<p><small>{monitor.reason}</small></p>}
        {Array.isArray(s.activeTasks)&&s.activeTasks.map((task,i)=><p key={String(task.id??i)}><small>Codex: {String(task.taskType??task.type??'Analysis')} · {human(String(task.status??'Running'))}</small></p>)}
        <button className="button secondary" disabled={busy||(!s.autonomous&&s.killed)} onClick={()=>void action('/api/v2/autonomy/sleeves/'+s.strategy,{enabled:!s.autonomous},`${names[s.strategy]??s.strategy} autonomy ${s.autonomous?'paused':'enabled'}.`)}>{s.autonomous?'Pause':'Enable'} {names[s.strategy]??s.strategy} autonomy</button>
        <details><summary>Structured strategy rules</summary>{s.behavior?<Rules value={s.behavior}/>:<p>Rules have not loaded.</p>}</details>
        {data.supervisor.config[s.strategy]&&<CadenceEditor key={JSON.stringify(data.supervisor.config[s.strategy])} strategy={s.strategy} value={data.supervisor.config[s.strategy]!} busy={busy} save={config=>action('/api/v2/autonomy/config',{strategy:s.strategy,config},`${names[s.strategy]??s.strategy} frequency updated.`)}/>}
      </article>;})}</div>
      <p className="muted">Describe strategy changes in the existing Codex input. Validated rules appear above and apply on subsequent runs. A sleeve kill switch remains latched until you complete its existing review and reset.</p>
      {data.supervisor.state.lastError&&<p className="form-error" role="alert">Supervisor: {data.supervisor.state.lastError}</p>}
      <details><summary>Recent autonomous activity</summary>{data.activity?.length?data.activity.slice(0,12).map((event,i)=><div className="history-row" key={event.at+event.kind+i}><div><b>{event.strategy?`${names[event.strategy]??event.strategy} · `:''}{human(event.kind)}</b><p>{event.message}</p></div><small>{when(event.at)}</small></div>):<p>No autonomous events recorded yet.</p>}</details>
    </>}
  </section>;
}
