import {useEffect,useState} from 'react';
import {api,post} from '../api';
import type {Proposal} from '../../packages/trading-v2/src/model';
type Fill={id:string;quantity:number;price:number;fees:number|null};
export function BrokerRecordReview({proposal,refresh,notify}:{proposal:Proposal|undefined;refresh:()=>Promise<void>;notify:(message:string,tone?:string)=>void}){
  const [fills,setFills]=useState<Fill[]>([]),[fillId,setFillId]=useState(''),[fees,setFees]=useState(''),[receipt,setReceipt]=useState(''),[brokerId,setBrokerId]=useState('');
  const load=async()=>{const state=await api<{account:{fills:Fill[]}|null}>('/api/v2/state');setFills((state.account?.fills??[]).filter(f=>f.fees===null));};
  useEffect(()=>{void load().catch(()=>undefined);},[proposal]);
  const act=async(path:string,body:unknown)=>{try{await post(path,body);await Promise.all([refresh(),load()]);notify('Broker records reviewed. No order was placed; trading remains paused.');}catch(e){notify(String(e),'danger');}};
  if(!fills.length&&proposal?.state!=='UNKNOWN_OUTCOME')return null;
  return <section className="panel product-card"><h3>Review broker records</h3><p className="safety-note">Unknown outcomes are never resubmitted automatically. Sync orders and fills, then review any missing broker facts.</p>{fills.length>0&&<><label className="field"><span>Fill with unavailable actual fees</span><select value={fillId} onChange={e=>setFillId(e.target.value)}><option value="">Choose verified fill</option>{fills.map(f=><option key={f.id} value={f.id}>{f.id} · {f.quantity} at ${f.price}</option>)}</select></label><label className="field"><span>Total actual fees for this fill from Robinhood receipt</span><input type="number" min="0" step="0.01" value={fees} onChange={e=>setFees(e.target.value)}/></label></>}
    {proposal?.state==='UNKNOWN_OUTCOME'&&<label className="field"><span>Exact Robinhood order ID (only if not already linked)</span><input value={brokerId} onChange={e=>setBrokerId(e.target.value)}/></label>}
    <label className="field"><span>Receipt reference and review</span><textarea value={receipt} onChange={e=>setReceipt(e.target.value)}/></label>{fills.length>0&&<button className="button secondary" disabled={!fillId||fees===''||receipt.length<20} onClick={()=>{if(window.confirm('Confirm these are ACTUAL fees from the Robinhood fill receipt, not preview estimates?'))void act('/api/v2/fill-fee-review',{fillId,fees:Number(fees),receipt,confirmation:'CONFIRM ACTUAL BROKER FILL FEES'});}}>Confirm actual fill fees</button>}{proposal?.state==='UNKNOWN_OUTCOME'&&<button className="button secondary" disabled={!brokerId||receipt.length<20} onClick={()=>{if(window.confirm('Confirm this exact broker order belongs to the uncertain submission? The app will verify its account and terms. This does not retry it.'))void act('/api/v2/proposals/'+proposal.id+'/link-unknown',{brokerOrderId:brokerId,review:receipt,confirmation:'LINK UNKNOWN BROKER ORDER'});}}>Link and reconcile existing broker order</button>}</section>;
}
