import {useCallback,useEffect,useState} from 'react';
import {api,post} from '../api';
import type {AppTask,TaskSchedule} from '../../packages/agents/src/task-service';
import type {TaskInput} from '../../packages/agents/src/task-contract';
import {SensitiveActionAuth} from './SensitiveActionAuth';
type Status={installed:boolean;loggedIn:boolean;usable:boolean;version:string|null;robinhood:{configured:boolean;status:string};active:number;queued:number;lastSuccess:string|null;lastError:string|null;settings:TaskInput['settings']};
export function CodexStatus(){const [s,set]=useState<Status|null>(null);useEffect(()=>{void api<Status>('/api/v2/codex/status').then(set).catch(()=>set(null));},[]);return <section className="panel product-card"><div className="card-kicker">LOCAL REASONING WORKER</div><h2>Codex</h2><p>{s?.usable?'Ready · ChatGPT login':'Unavailable · dashboard and safety controls remain available'}</p><dl><dt>Installed</dt><dd>{s?.version??'Not detected'}</dd><dt>ChatGPT login</dt><dd>{s?.loggedIn?'Logged in':'Needs login'}</dd><dt>Robinhood MCP</dt><dd>{s?.robinhood.status??'Unavailable'}</dd><dt>Tasks</dt><dd>{s?.active??0} running · {s?.queued??0} queued</dd><dt>Last success</dt><dd>{s?.lastSuccess??'No completed task'}</dd></dl>{s?.lastError&&<p role="status">{s.lastError}</p>}<p>No OpenAI API key or paid API fallback. Broker reads do not grant trading authority.</p></section>;}
export function CodexTasks({notify,compact=false}:{notify:(message:string,tone?:string)=>void;compact?:boolean}){
  const [tasks,setTasks]=useState<AppTask[]>([]),[schedules,setSchedules]=useState<TaskSchedule[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('All'),[settings,setSettings]=useState<TaskInput['settings']|null>(null);
  const [changes,setChanges]=useState<Array<{id:string;reason:string;payload:unknown;status:string}>>([]);
  const [cadence,setCadence]=useState(1440),[scheduleType,setScheduleType]=useState<TaskInput['type']>('DAILY_REPORT'),[strategy,setStrategy]=useState<TaskInput['strategy']>(null);
  const load=useCallback(async()=>{const [jobs,scheduled,pending]=await Promise.all([api<AppTask[]>('/api/v2/codex/tasks'),api<TaskSchedule[]>('/api/v2/codex/schedules'),api<{changes:Array<{id:string;reason:string;payload:unknown;status:string}>}>('/api/changes')]);setTasks(jobs);setSchedules(scheduled);setChanges(pending.changes.filter(c=>c.status==='PENDING'));},[]);
  useEffect(()=>{void load().catch(e=>notify(String(e),'danger'));void api<Status>('/api/v2/codex/status').then(s=>setSettings(s.settings)).catch(()=>undefined);const t=setInterval(()=>void load().catch(()=>undefined),2500);return()=>clearInterval(t);},[load,notify]);
  const perform=async(work:()=>Promise<unknown>)=>{setBusy(true);try{await work();await load();}catch(e){notify(String(e),'danger');}finally{setBusy(false);}};
  const submit=()=>perform(async()=>{await post('/api/v2/codex/tasks',{message:text,id:crypto.randomUUID()});setText('');});
  const addSchedule=()=>perform(async()=>{await post('/api/v2/codex/schedules',{name:text.slice(0,80),message:text,type:scheduleType,authority:scheduleType==='GENERATE_TRADE_PROPOSAL'?'TRADE_PROPOSAL':scheduleType==='RESEARCH_SYMBOL'?'RESEARCH':'READ_ONLY',strategy,intervalMinutes:cadence,enabled:true,timeoutMs:settings?.timeoutMs??120000});notify('Local schedule saved. First run follows the selected interval.');});
  const visible=tasks.filter(t=>filter==='All'||filter==='Results'&&t.status==='COMPLETED'||filter==='Failed'&&['FAILED','UNKNOWN','TIMED_OUT','BLOCKED_USAGE_LIMIT'].includes(t.status)||filter==='Running'&&t.status==='RUNNING'||filter==='Queued'&&t.status==='QUEUED');
  return <div className="product-stack codex-tasks"><div className="page-intro"><h2>What do you want Codex to do?</h2><p>Each request is a bounded task. Proposals require review; trading safety stays in the app.</p></div>{!compact&&<CodexStatus/>}
    <form className="panel product-card" onSubmit={e=>{e.preventDefault();void submit();}}><label className="field"><span>Your request</span><textarea rows={3} maxLength={12000} value={text} onChange={e=>setText(e.target.value)} placeholder="Review my account, explain a rejection, or request a change…"/></label><button className="button primary" disabled={busy||!text.trim()}>Run task</button><div className="assistant-prompts">{['Review my account','Review my options positions','Generate a trade proposal','Explain this rejection','Run a strategy review','Pause aggressive trading','Summarize today','Run the full system test'].map(p=><button key={p} type="button" onClick={()=>setText(p)}>{p}</button>)}</div></form>
    {!compact&&<details className="panel product-card"><summary>Scheduled tasks ({schedules.length})</summary><p>Runs locally on the Pi, even when this page is closed. Missed occurrences become one run.</p><label className="field">Task type<select value={scheduleType} onChange={e=>setScheduleType(e.target.value as TaskInput['type'])}>{['DAILY_REPORT','WEEKLY_REPORT','REVIEW_STRATEGY','REVIEW_OPTIONS','REVIEW_POSITION','RESEARCH_SYMBOL','GENERATE_TRADE_PROPOSAL'].map(t=><option key={t}>{t}</option>)}</select></label><label className="field">Target sleeve<select value={strategy??''} onChange={e=>setStrategy((e.target.value||null) as TaskInput['strategy'])}><option value="">Account</option>{['SAFE_LONG_TERM','AGGRESSIVE_STOCKS','OPTIONS'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Cadence<select value={cadence} onChange={e=>setCadence(Number(e.target.value))}><option value={60}>Hourly</option><option value={240}>Every four hours</option><option value={1440}>Daily</option><option value={10080}>Weekly</option></select></label><button disabled={busy||!text.trim()} onClick={()=>void addSchedule()}>Schedule the request above</button>{schedules.map(s=><article key={s.id}><h3>{s.name}</h3><p>{s.authority} · {s.enabled?'Enabled':'Disabled'} · next {new Date(s.nextRun).toLocaleString()} · last {s.lastRun??'Never'}</p><button onClick={()=>void perform(()=>post('/api/v2/codex/schedules/'+s.id,{name:s.name,message:s.message,type:s.type,authority:s.authority,strategy:s.strategy,intervalMinutes:s.intervalMinutes,enabled:!s.enabled,timeoutMs:s.timeoutMs}))}>{s.enabled?'Disable':'Enable'}</button></article>)}</details>}
    {!compact&&settings&&<details className="panel product-card"><summary>Worker settings</summary><p>Blank model and effort use CLI defaults. Unsupported combinations fail safely.</p><label className="field">Model<input value={settings.model??''} onChange={e=>setSettings({...settings,model:e.target.value||null})}/></label><label className="field">Reasoning effort<select value={settings.effort??''} onChange={e=>setSettings({...settings,effort:(e.target.value||null) as TaskInput['settings']['effort']})}><option value="">Default</option>{['low','medium','high','xhigh'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Timeout (seconds)<input type="number" min={10} max={600} value={settings.timeoutMs/1000} onChange={e=>setSettings({...settings,timeoutMs:Number(e.target.value)*1000})}/></label><label className="field">Concurrent tasks<input type="number" min={1} max={4} value={settings.concurrency} onChange={e=>setSettings({...settings,concurrency:Number(e.target.value)})}/></label><button onClick={()=>void perform(()=>post('/api/v2/codex/settings',settings))}>Save settings</button></details>}
    {changes.length>0&&<SensitiveActionAuth notify={notify}/>} {changes.map(c=><article className="panel product-card" key={c.id}><h3>Review proposed change</h3><p>{c.reason}</p><pre>{JSON.stringify(c.payload,null,2)}</pre><button onClick={()=>void perform(()=>post('/api/changes/'+c.id+'/reject',{}))}>Reject</button><button onClick={()=>{if(window.confirm('Apply exactly this configuration change? This does not approve a trade.'))void perform(()=>post('/api/changes/'+c.id+'/confirm',{}));}}>Confirm change</button></article>)}
    <section className="panel product-card"><h2>Task history & reports</h2><div className="assistant-prompts">{['All','Running','Queued','Results','Failed'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{!visible.length&&<p>No tasks in this view.</p>}{visible.map(t=><article className="codex-task-result" key={t.id}><header><strong>{t.message}</strong><span className="tag">{t.status.replaceAll('_',' ')}</span></header><small>{t.source} · {t.type.replaceAll('_',' ')} · {new Date(t.createdAt).toLocaleString()} · {t.durationMs===null?'—':Math.round(t.durationMs/1000)+'s'}</small>{t.response&&<p style={{whiteSpace:'pre-wrap'}}>{t.response.message}</p>}{t.error&&<p role="status">{t.error}</p>}{t.response?.action&&<details><summary>Proposed action & application result</summary><pre>{JSON.stringify({action:t.response.action,result:t.result},null,2)}</pre><p>Draft trades remain in Trade reviews. Execution requires all existing gates.</p></details>}{['QUEUED','RUNNING'].includes(t.status)&&<button onClick={()=>void perform(()=>post('/api/v2/codex/tasks/'+t.id+'/cancel',{}))}>Cancel task</button>}<details><summary>Advanced · audit & CLI logs</summary><pre>{JSON.stringify({id:t.id,authority:t.authority,template:t.templateVersion,version:t.version,hash:t.hash,sources:t.response?.sources,stdout:t.stdout,stderr:t.stderr},null,2)}</pre></details></article>)}</section>
  </div>;
}
