import {useCallback,useEffect,useState} from 'react';
import {api,post} from '../api';
import {OpenAIConnectionSetup} from './OpenAIConnectionSetup';

export interface ConnectionData {
  connectors: Array<{id:string;state:string;configured:boolean;lastSuccess:string|null;lastError:string|null;details:Record<string,unknown>}>;
  setup:{ready:boolean;callbackUrl:string|null;message:string|null;code:string|null;accountMapped:boolean;bindingConfigured:boolean;mode:string};
  network:unknown;
}
export const connectionLabel=(state:string,configured:boolean)=>({CONNECTED:'Connected',READ_ONLY:'Account verified · read only',AUTH_EXPIRED:'Sign in again',ERROR:'Needs attention',LIVE_CAPABLE:'Connected'}[state]??(configured?'Saved · check connection':'Not connected'));
export function ConnectionGuide({notify}:{notify:(message:string,tone?:string)=>void}) {
  const [data,setData]=useState<ConnectionData|null>(null),[error,setError]=useState(''),[password,setPassword]=useState(''),[connecting,setConnecting]=useState(false),[busy,setBusy]=useState('');
  const load=useCallback(async()=>{try{setData(await api<ConnectionData>('/api/v2/connections'));}catch(e){setError(e instanceof Error?e.message:String(e));}},[]);
  useEffect(()=>{void load();const query=new URLSearchParams(location.search);if(query.has('connectionError')){setError('Robinhood sign-in did not finish. Reconnect below. If it repeats, check the return address in Connection details. Diagnostic code: '+query.get('connectionError'));}else if(query.has('connection')){notify('Robinhood sign-in returned. Check the connection, then sync your account.');}if(query.has('connection')||query.has('connectionError'))history.replaceState(null,'',location.pathname);},[load,notify]);
  const action=async(id:string,connect=false)=>{setBusy(id);setError('');try{
    if(connect){await post('/api/v2/reauth',{password});setPassword('');}
    const result=await post<{authorizationUrl?:string;state?:string;lastError?:string}>('/api/v2/connections/'+id+'/'+(connect?'connect':'test'),{});
    if(result.authorizationUrl){window.location.assign(result.authorizationUrl);return;}
    await load();if(result.state==='ERROR'||result.state==='AUTH_EXPIRED')setError(result.lastError??'Connection needs attention.');else notify('Connection checked. Real trading remains disabled.');
  }catch(e){setError(e instanceof Error?e.message:String(e));await load();}finally{setBusy('');setPassword('');}};
  const sync=async()=>{setBusy('sync');setError('');try{const result=await post<{clear:boolean;mismatches:string[]}>('/api/v2/reconciliation',{});await load();if(result.clear)notify('Account synced and verified. Real trading remains disabled.');else setError('Account sync found differences. Open More tools → Reconciliation to review them. Trading remains blocked. '+result.mismatches.join('; '));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('');}};
  const robinhood=data?.connectors.find(c=>c.id==='ROBINHOOD');
  return <div className="product-stack"><div className="page-intro"><h2>Connect at your own pace.</h2><p>Simulation works without either service. Add the assistant, then link your account for a verified, read-only view.</p></div>
    <div className="safety-note">Real trading is disabled in this release. Connecting services does not enable it.</div>
    {error&&<div className="inline-error" role="alert"><strong>Connection needs attention</strong><p>{error}</p><button onClick={()=>void load()}>Refresh connection status</button></div>}
    <div className="connection-grid"><section className="panel product-card"><div className="card-kicker">01 / YOUR ASSISTANT</div><h2>OpenAI</h2><p>Ask questions, understand positions, and request changes for review.</p><p className="status-text">{data?connectionLabel(data.connectors.find(c=>c.id==='OPENAI')?.state??'',data.connectors.find(c=>c.id==='OPENAI')?.configured??false):'Checking…'}</p><OpenAIConnectionSetup notify={notify} onSaved={load}/><button disabled={!!busy||!data?.connectors.find(c=>c.id==='OPENAI')?.configured} onClick={()=>void action('openai')}>{busy==='openai'?'Checking…':'Check OpenAI access'}</button>{data?.connectors.find(c=>c.id==='OPENAI')?.lastError&&<p role="status">{data.connectors.find(c=>c.id==='OPENAI')?.lastError}. Check the API key and model access in your OpenAI account.</p>}</section>
    <section className="panel product-card"><div className="card-kicker">02 / YOUR BROKERAGE</div><h2>Robinhood</h2><p>Sign in on Robinhood’s authorization page. Your Robinhood password is never entered here.</p><p className="status-text">{robinhood?connectionLabel(robinhood.state,robinhood.configured):'Checking…'}</p>{data&&!data.setup.ready&&<div className="inline-error"><p>{data.setup.message}</p></div>}
      {connecting?<form onSubmit={e=>{e.preventDefault();void action('robinhood',true);}}><label>Your app password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><small>Confirm it once to protect account linking.</small><button className="button primary" disabled={!!busy||!password}>{busy==='robinhood'?'Opening Robinhood…':'Continue to Robinhood'}</button><button type="button" onClick={()=>{setConnecting(false);setPassword('');}}>Cancel</button></form>:<button className="button primary" disabled={!data?.setup.ready||!!busy} onClick={()=>setConnecting(true)}>Connect Robinhood</button>}
      <button disabled={!!busy||!robinhood?.configured} onClick={()=>void action('robinhood')}>Check Robinhood connection</button>{robinhood?.lastError&&<p className="negative">{robinhood.lastError}</p>}
    </section></div>
    <section className="panel product-card"><div className="card-kicker">03 / VERIFY YOUR ACCOUNT</div><h2>Sync before you rely on the numbers.</h2><p>After connecting, compare your account, holdings, and open orders with Robinhood. This step places no trades.</p>{data?.setup.mode==='SIMULATION'?<p>Currently using practice money. Switch to Read Only in Settings after configuring the account mapping.</p>:null}{data&&(!data.setup.accountMapped||!data.setup.bindingConfigured)&&<p className="setup-instruction">Your Pi still needs a reviewed account mapping. Set <code>ROBINHOOD_AGENTIC_ACCOUNT_ID</code> and <code>ROBINHOOD_BINDING_FILE</code> in its protected environment, then restart. Authorization alone cannot supply a verified mapping.</p>}<button disabled={!!busy||!data?.setup.accountMapped||!data.setup.bindingConfigured||data.setup.mode==='SIMULATION'||!['CONNECTED','READ_ONLY'].includes(robinhood?.state??'')} onClick={()=>void sync()}>{busy==='sync'?'Syncing…':'Sync read-only account'}</button></section>
    <details className="panel product-card"><summary>Connection details & troubleshooting</summary><p>Use Tailscale Serve HTTPS with the app bound to localhost. Set PRIVATE_UI_URL and WEB_ORIGIN to the same origin. Forwarded headers are never trusted to choose a callback.</p><p>Return address: <code>{data?.setup.callbackUrl??'Not configured'}</code></p><p>Order placement stays locked. Available previews depend on the capabilities returned by Robinhood.</p><pre>{JSON.stringify(data,null,2)}</pre></details>
  </div>;
}
