import {useState} from 'react';
import {post} from '../api';
const actions=['STOP_NEW_TRADES','CANCEL_OPEN_ENTRIES','PAUSE_SAFE','PAUSE_AGGRESSIVE','PAUSE_OPTIONS','CLOSE_AGGRESSIVE','CLOSE_OPTIONS','LIQUIDATE_ALL'];
export function EmergencyControls({notify}:{notify:(message:string,tone?:string)=>void}){
  const [action,setAction]=useState(actions[0]!),[confirmation,setConfirmation]=useState(''),[reason,setReason]=useState(''),[password,setPassword]=useState(''),[result,setResult]=useState<unknown>(null),[busy,setBusy]=useState(false);
  const sensitive=action.startsWith('CLOSE')||action==='LIQUIDATE_ALL'||action==='CANCEL_OPEN_ENTRIES';
  const submit=async()=>{setBusy(true);try{if(sensitive)await post('/api/v2/reauth',{password});setPassword('');setResult(await post('/api/v2/emergency',{action,confirmation,reason}));notify('Emergency control recorded. Review its exact result.');}catch(e){notify(String(e),'danger');}finally{setBusy(false);}};
  return <section className="panel terminal-panel"><h2>Deterministic emergency controls</h2><p className="muted">No agent is required. CLOSE and LIQUIDATE prepare owned-position closing drafts only in this pass; they do not place orders. Fresh research, risk, preview and individual manual approval remain mandatory. Uncertain orders cannot be cancelled locally.</p><div className="terminal-toolbar"><label>Action<select value={action} onChange={e=>{setAction(e.target.value);setConfirmation('');setResult(null);}}>{actions.map(a=><option key={a}>{a}</option>)}</select></label><label>Exact confirmation<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={action}/></label></div><label>Review / reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{sensitive&&<label>Reauthenticate<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="emergency-button" disabled={busy||confirmation!==action||reason.length<20||sensitive&&!password} onClick={()=>void submit()}>Confirm {action.replaceAll('_',' ')}</button>{result!==null&&<pre className="terminal-json">{JSON.stringify(result,null,2)}</pre>}</section>;
}
