import { useState } from 'react';
import { BrainCircuit, Check, ChevronRight, MessageSquareText, Send, ShieldCheck, X } from 'lucide-react';
import { post } from '../api';

interface Message { role: 'manager' | 'operator'; text: string; kind?: string; pending?: { id: string; type: string; summary: string; expiresAt: string }; data?: unknown }

export function ManagerChat({ open, close, refresh, notify }: { open: boolean; close: () => void; refresh: () => Promise<void>; notify: (message: string, tone?: string) => void }) {
  const [messages, setMessages] = useState<Message[]>([{ role: 'manager', text: 'I can explain decisions, compare agents, or prepare confirmable changes. I cannot turn chat directly into an order.', kind: 'INFORMATIONAL RESPONSE' }]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false);
  const send = async (value = input) => { const trimmed = value.trim(); if (!trimmed) return; setMessages((current) => [...current, { role: 'operator', text: trimmed }]); setInput(''); setBusy(true); try { const reply = await post<{ kind: string; message: string; pendingChange?: Message['pending']; data?: unknown }>('/api/manager/chat', { message: trimmed }); setMessages((current) => [...current, { role: 'manager', text: reply.message, kind: reply.kind.replaceAll('_', ' '), ...(reply.pendingChange ? { pending: reply.pendingChange } : {}), data: reply.data }]); } catch (cause) { setMessages((current) => [...current, { role: 'manager', text: cause instanceof Error ? cause.message : String(cause), kind: 'ERROR' }]); } finally { setBusy(false); } };
  const confirm = async (id: string) => { try { await post(`/api/changes/${id}/confirm`, {}); setMessages((current) => current.map((message) => { if (message.pending?.id !== id) return message; return { role: message.role, text: `${message.text} Confirmed and committed.`, ...(message.kind ? { kind: message.kind } : {}), ...(message.data !== undefined ? { data: message.data } : {}) }; })); notify('Manager change confirmed and audit logged.'); await refresh(); } catch (cause) { notify(cause instanceof Error ? cause.message : String(cause), 'danger'); } };
  const examples = ['Pause day trading today.', "Look into RKLB but don't trade it.", 'Which agent has performed best?', 'Explain why the day trader evaluated NVDA.'];
  return <aside className={`chat-drawer ${open ? 'open' : ''}`} aria-hidden={!open}>
    <header><div className="manager-avatar"><BrainCircuit /></div><div><p className="eyebrow">MANAGER AGENT</p><h2>Operator channel</h2><span><i /> IDLE · authority constrained</span></div><button className="icon-button" onClick={close}><X /></button></header>
    <div className="chat-contract"><ShieldCheck /><span><b>Conversation is not execution.</b> Material changes require a structured confirmation; trades require the full deterministic pipeline.</span></div>
    <div className="messages">{messages.map((message, index) => <article className={`message ${message.role}`} key={index}>{message.kind && <span className={`message-kind ${message.kind.toLowerCase().includes('proposed') ? 'proposed' : ''}`}>{message.kind}</span>}<p>{message.text}</p>{Array.isArray(message.data) && <div className="message-data">{message.data.slice(0, 5).map((item, itemIndex) => <span key={itemIndex}>{Object.entries(item as Record<string, unknown>).slice(0, 3).map(([key, value]) => <i key={key}><b>{key}</b>{String(value ?? '—')}</i>)}</span>)}</div>}{message.pending && <div className="pending-card"><span>STRUCTURED CHANGE</span><h3>{message.pending.summary}</h3><small>{message.pending.type.replaceAll('_', ' ')}</small><div><button className="button secondary" onClick={() => void post(`/api/changes/${message.pending?.id}/reject`, {})}>Reject</button><button className="button primary" onClick={() => void confirm(message.pending!.id)}><Check /> Confirm</button></div></div>}</article>)}{busy && <article className="message manager typing"><span /><span /><span /></article>}</div>
    {messages.length <= 1 && <div className="chat-examples"><span>TRY A CONTROLLED REQUEST</span>{examples.map((example) => <button key={example} onClick={() => void send(example)}>{example}<ChevronRight /></button>)}</div>}
    <form className="chat-input" onSubmit={(event) => { event.preventDefault(); void send(); }}><MessageSquareText /><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask, explain, or propose a change…" rows={2} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send(); } }} /><button disabled={busy || !input.trim()}><Send /></button></form>
  </aside>;
}
