import {useEffect,useState} from 'react';
import {api,post} from '../api';
import {SensitiveActionAuth} from './SensitiveActionAuth';
type Readiness={ready:boolean;mode:string;checks:Record<string,boolean>;limitation:string};
const labels:Record<string,string>={calendarVerified:'Exchange calendar freshly verified',correctAccount:'Correct Agentic account',freshAccount:'Account freshly synced',cleanReconciliation:'Account differences resolved',reviewedOpening:'Opening cash reviewed',reviewedOwnership:'Holdings assigned and reviewed',robinhoodAvailable:'Robinhood connected',brokerReviewVerified:'Official order review verified',executionCapabilities:'Placement and cancellation available',deterministicRiskHealthy:'Risk safety checks passed for these settings',emergencyStopHealthy:'Emergency STOP available',noUnknownOrders:'No uncertain order outcomes',manualApprovalOnly:'You approve each transaction',pauseReleased:'Global pause deliberately released',stopReleased:'STOP released',maintenanceOff:'Maintenance off'};
export function ManualLivePanel({notify}:{notify:(message:string,tone?:string)=>void}){
  const [data,setData]=useState<Readiness|null>(null),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState('');
  const load=async()=>setData(await api<Readiness>('/api/v2/readiness'));
  useEffect(()=>{void load().catch(e=>notify(String(e),'danger'));},[]);
  const action=async(path:string,body:unknown={})=>{setBusy(true);try{await post(path,body);await load();notify('Check recorded. No order was placed.');}catch(e){notify(e instanceof Error?e.message:String(e),'danger');await load();}finally{setBusy(false);}};
  return <div className="terminal-stack"><section className="panel product-card"><p className="eyebrow">YOU CONTROL LIVE TRADING</p><h2>Manual live readiness</h2><p>Sync your account → review imported holdings and opening cash → resolve differences → verify broker review and safety → deliberately enable Manual Live.</p><p className="safety-note">{data?.mode==='LIVE'?'MANUAL LIVE': 'READ ONLY'} · {data?.checks.stopReleased===false?'STOPPED':data?.checks.pauseReleased===false?'PAUSED':data?.checks.cleanReconciliation===false?'RECONCILIATION REQUIRED':data?.ready?'READY':'REVIEW REQUIRED'}. Every trade needs your approval and a separate submission.</p><div className="assertion-list">{Object.entries(data?.checks??{}).map(([k,v])=><div key={k}><b className={v?'positive':'muted'}>{v?'PASS':'NEEDED'}</b><span>{labels[k]??k}</span></div>)}</div><p>{data?.limitation}</p><div className="v2-actions"><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/reconciliation')}>Sync and check account</button><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/commission/check')}>Check official broker review</button><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/self-tests')}>Check risk and STOP safety</button></div><p className="muted">Broker review checks an existing holding without placing an order. Safety checks use isolated simulated money. Imported basis may remain unavailable; a sale requiring realized P&L will explicitly reject until its basis is verified.</p><SensitiveActionAuth notify={notify}/><button className="button secondary" disabled={busy||data?.checks.pauseReleased} onClick={()=>{if(window.confirm('Release global pause? Read only still prevents orders until you separately enable Manual Live.'))void action('/api/system/pause',{paused:false});}}>Release global pause</button><label className="field"><span>Type ENABLE LIVE TRADING</span><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="button primary" disabled={busy||!data?.ready||confirmation!=='ENABLE LIVE TRADING'} onClick={()=>void action('/api/system/mode',{mode:'LIVE',confirmation})}>Enable Manual Live</button><button className="button secondary" disabled={busy} onClick={()=>void action('/api/system/mode',{mode:'READ_ONLY'})}>Return to Read only</button></section></div>;
}
