import { useState } from 'react';
import { Check, ChevronLeft, ChevronRight, LockKeyhole, ShieldCheck, WalletCards } from 'lucide-react';
import { post } from '../api';

export interface SetupStatus { complete: boolean; hasAdmin: boolean; mode: string; strategies: Array<{ id: string; name: string; allocationAmount: number }>; checks: Record<string, { ok: boolean; message: string }>; exampleDefaults: boolean }

export function SetupWizard({ status, onComplete }: { status: SetupStatus; onComplete: (csrf: string) => void }) {
  const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [username,setUsername]=useState('operator'),[password,setPassword]=useState(''),[demoData,setDemoData]=useState(true),[capital,setCapital]=useState(50000);
  const [allocations,setAllocations]=useState<Record<string,number>>(()=>Object.fromEntries(status.strategies.map(s=>[s.id,s.allocationAmount])));
  const total=Object.values(allocations).reduce((n,v)=>n+v,0);
  const valid=Number.isFinite(capital)&&capital>=100&&total<=capital&&Object.values(allocations).every(v=>Number.isFinite(v)&&v>=0);
  const finish=async()=>{setBusy(true);setError('');try{const result=await post<{csrf:string}>('/api/setup/complete',{username,password,designatedCapital:capital,allocations,demoData});onComplete(result.csrf);}catch(e){setError(e instanceof Error?e.message:String(e));setBusy(false);}};
  return <main className="setup-shell"><aside className="setup-rail"><div className="setup-brand"><span>A</span> Agentic</div><p>LET'S GET STARTED</p>{['Try it safely','Protect your account','Ready to explore'].map((label,i)=><div className={'setup-step '+(i===step?'active':i<step?'done':'')} key={label}><i>{i<step?<Check size={13}/>:i+1}</i><span>{label}</span></div>)}<div className="setup-safety"><ShieldCheck/><span>Real trading stays disabled.</span></div></aside><section className="setup-main"><header><p className="eyebrow">STEP {step+1} OF 3</p><span className="simulation-pill">PRACTICE MONEY ONLY</span></header><div className="setup-content">
  {step===0&&<><p className="eyebrow">WELCOME TO AGENTIC</p><h1>Understand your money.<br/>Start without risking it.</h1><p className="lede">Follow three strategies, explore trades with an assistant, and keep every action within your controls. Start with a practice account; connect OpenAI and Robinhood later.</p><div className="review-grid"><article><WalletCards/><span>Practice balance</span><strong>{money(capital)}</strong></article><article><ShieldCheck/><span>Real trading</span><strong>Disabled</strong></article></div><details><summary>Customize practice money</summary><label className="field"><span>Practice account balance ($)</span><input type="number" min={100} value={capital} onChange={e=>setCapital(Number(e.target.value))}/></label>{status.strategies.map(strategy=><label className="field" key={strategy.id}><span>{strategy.name} ($)</span><input type="number" min={0} value={allocations[strategy.id]??0} onChange={e=>setAllocations({...allocations,[strategy.id]:Number(e.target.value)})}/></label>)}<p>Assigned: {money(total)} of {money(capital)}</p>{!valid&&<p role="alert">Use a balance of at least $100 and assign no more than that total.</p>}</details><details><summary>Device checks</summary>{Object.entries(status.checks).map(([name,c])=><p key={name}>{c.ok?'Ready':'Needs review'}: {name} - {c.message}</p>)}</details></>}
  {step===1&&<><h1>Make this space yours.</h1><p className="lede">Choose a password for this app. It is separate from your Robinhood and OpenAI accounts.</p><label className="field"><span>Username</span><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="field"><span>App password (at least 12 characters)</span><input type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} aria-describedby="password-help"/></label><p id="password-help">You will use this to sign in and confirm important changes.</p></>}
  {step===2&&<><h1>Your practice account is ready.</h1><p className="lede">You will start with {money(capital)} in simulated funds, split across Safe, Aggressive, and Options. Nothing here connects to or trades with real money.</p><dl className="plain-facts">{status.strategies.map(s=><div key={s.id}><dt>{s.name}</dt><dd>{money(allocations[s.id]??0)}</dd></div>)}</dl><label className="toggle-row"><input type="checkbox" checked={demoData} onChange={e=>setDemoData(e.target.checked)}/><span><b>Include sample holdings and activity</b><small>Explore the interface with clearly marked practice data.</small></span></label><div className="callout"><ShieldCheck/><span>Next, run a safe simulation from your account page. We will guide you through connecting services when you are ready.</span></div></>}
  {error&&<div className="form-error" role="alert">{error}</div>}</div><footer><button className="button secondary" disabled={step===0||busy} onClick={()=>setStep(step-1)}><ChevronLeft size={16}/>Back</button>{step<2?<button className="button primary" disabled={!valid||(step===1&&(password.length<12||!username.trim()))} onClick={()=>setStep(step+1)}>Continue<ChevronRight size={16}/></button>:<button className="button primary" disabled={busy||!valid||password.length<12} onClick={()=>void finish()}>{busy?'Creating your practice account…':'Open my practice account'}</button>}</footer></section></main>;
}

export function LoginScreen({ onAuthenticated }: { onAuthenticated: (csrf: string) => void }) {
  const [username, setUsername] = useState('operator'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const login = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await post<{ csrf: string }>('/api/auth/login', { username, password }); onAuthenticated(result.csrf); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); setBusy(false); } };
  return <main className="login-shell"><section className="login-brand"><div className="large-mark">A</div><p className="eyebrow">AGENTIC TRADING MANAGER</p><h1>Your account. Your strategies. Your control.</h1><p>Start with practice money. Connect when you are ready.</p></section><form className="login-card" onSubmit={(event) => void login(event)}><div className="login-icon"><LockKeyhole /></div><p className="eyebrow">CONTROL ROOM ACCESS</p><h2>Welcome back.</h2><label className="field"><span>Username</span><input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" autoFocus /></label><label className="field"><span>Password</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></label>{error && <div className="form-error">{error}</div>}<button className="button primary wide" disabled={busy}>{busy ? 'Authenticating…' : 'Sign in'}</button><p className="login-foot">Your app password protects access to this dashboard.</p></form></main>;
}

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
