import { useMemo, useState } from 'react';
import { Activity, Bot, Check, ChevronLeft, ChevronRight, Database, LockKeyhole, Network, ShieldCheck, WalletCards } from 'lucide-react';
import { post } from '../api';

export interface SetupStatus { complete: boolean; hasAdmin: boolean; mode: string; strategies: Array<{ id: string; name: string; allocationAmount: number }>; checks: Record<string, { ok: boolean; message: string }>; exampleDefaults: boolean }
const steps = ['Welcome', 'System check', 'Strategies', 'Allocations', 'Risk + security', 'Review'];

export function SetupWizard({ status, onComplete }: { status: SetupStatus; onComplete: (csrf: string) => void }) {
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [capital, setCapital] = useState(50_000); const [demoData, setDemoData] = useState(true); const [username, setUsername] = useState('operator'); const [password, setPassword] = useState('');
  const [allocations, setAllocations] = useState<Record<string, number>>(() => Object.fromEntries(status.strategies.map((strategy) => [strategy.id, strategy.allocationAmount])));
  const total = useMemo(() => Object.values(allocations).reduce((sum, amount) => sum + Number(amount || 0), 0), [allocations]);
  const valid = step !== 3 || (total <= capital && total >= 0);

  const finish = async () => {
    if (password.length < 12) { setError('Use at least 12 characters for the administrator password.'); return; }
    setBusy(true); setError('');
    try { const result = await post<{ csrf: string }>('/api/setup/complete', { username, password, designatedCapital: capital, allocations, demoData }); onComplete(result.csrf); }
    catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); setBusy(false); }
  };

  return <main className="setup-shell">
    <aside className="setup-rail"><div className="setup-brand"><span>A</span> Agentic</div><p>FIRST-RUN COMMISSIONING</p>{steps.map((label, index) => <div className={`setup-step ${index === step ? 'active' : ''} ${index < step ? 'done' : ''}`} key={label}><i>{index < step ? <Check size={13} /> : index + 1}</i><span>{label}</span></div>)}<div className="setup-safety"><ShieldCheck size={18} /><div><b>Safe by default</b><span>Setup cannot enable live trading.</span></div></div></aside>
    <section className="setup-main">
      <header><p className="eyebrow">STEP {step + 1} OF {steps.length}</p><span className="simulation-pill">SIMULATION LOCKED</span></header>
      <div className="setup-content">
        {step === 0 && <div className="setup-copy"><div className="large-mark">A</div><p className="eyebrow">AGENTIC TRADING MANAGER V2</p><h1>Intelligence, held behind authority.</h1><p>This guided setup creates SAFE, AGGRESSIVE and OPTIONS ledgers in Simulation. These example funds are not your broker balance; LIVE integration is currently unavailable.</p><div className="callout"><LockKeyhole size={18} /><span>The persistent OpenAI agent uses typed application tools. Application code alone owns execution authority and hard limits.</span></div></div>}
        {step === 1 && <div><p className="eyebrow">SYSTEM READINESS</p><h1>Foundation checks</h1><p className="lede">Verify the local services required for persistent, observable operation.</p><div className="check-grid">{Object.entries(status.checks).map(([name, check]) => <article key={name}><span className={check.ok ? 'check-ok' : 'check-warn'}>{name === 'database' ? <Database /> : name === 'codex' ? <Bot /> : name === 'storage' ? <WalletCards /> : <Network />}</span><div><b>{name}</b><p>{check.message}</p></div><i>{check.ok ? 'READY' : 'CHECK'}</i></article>)}</div><div className="robinhood-note"><Network size={20} /><div><b>Robinhood can be linked later</b><p>Complete setup in Simulation. Then authenticate the official Trading MCP and validate Read Only before considering Live.</p></div></div></div>}
        {step === 2 && <div><p className="eyebrow">STRATEGY SLEEVES</p><h1>Three independent mandates</h1><p className="lede">Weekly targets default to one third of verified net account value, not buying power.</p><div className="onboard-strategies">{status.strategies.map((strategy, index) => <article key={strategy.id}><span className={`strategy-glyph tone-${index}`}>{index === 0 ? 'S' : index === 1 ? 'A' : 'O'}</span><div><h3>{strategy.name}</h3><p>{index === 0 ? 'Low-turnover long-term stocks and ETFs; no options' : index === 1 ? 'Liquid long stocks; intraday to short-term; no options' : 'Single-leg Level 2 options with owned collateral'}</p></div><span>MANUAL APPROVAL DEFAULT</span></article>)}</div><p className="fine-print">Defaults demonstrate configuration only. They are not financial recommendations and make no profitability claim.</p></div>}
        {step === 3 && <div><p className="eyebrow">VIRTUAL CAPITAL</p><h1>Allocate designated capital</h1><p className="lede">Allocations define economic ownership inside one brokerage account. They may total less than the designated amount.</p><label className="field"><span>Designated capital</span><div className="money-input"><i>$</i><input type="number" min="100" value={capital} onChange={(event) => setCapital(Number(event.target.value))} /></div></label><div className="allocation-list">{status.strategies.map((strategy) => <label key={strategy.id}><span>{strategy.name}</span><div className="money-input compact"><i>$</i><input type="number" min="0" value={allocations[strategy.id] ?? 0} onChange={(event) => setAllocations({ ...allocations, [strategy.id]: Number(event.target.value) })} /></div></label>)}</div><div className={`allocation-total ${total > capital ? 'over' : ''}`}><span>Allocated</span><strong>{money(total)} / {money(capital)}</strong><div><i style={{ width: `${Math.min(100, capital ? total / capital * 100 : 0)}%` }} /></div></div></div>}
        {step === 4 && <div><p className="eyebrow">ADMIN SECURITY</p><h1>Protect the control room</h1><p className="lede">Use a unique local password even when the dashboard is available only through Tailscale.</p><div className="security-grid"><label className="field"><span>Administrator username</span><input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label className="field"><span>Password · 12+ characters</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></label><label className="toggle-row"><input type="checkbox" checked={demoData} onChange={(event) => setDemoData(event.target.checked)} /><span><b>Seed clearly labeled simulation data</b><small>Add example fills, shared-ticker ownership, risk events, and performance history.</small></span></label></div><div className="risk-summary"><ShieldCheck /><div><b>Initial safety posture</b><p>Simulation mode · options off · crypto off · no margin behavior · reconciliation gate on · live confirmation absent</p></div></div></div>}
        {step === 5 && <div><p className="eyebrow">FINAL REVIEW</p><h1>Commission in Simulation</h1><p className="lede">This action initializes your admin account and versioned strategy allocations. It does not connect Robinhood or enable Live.</p><div className="review-grid"><article><Activity /><span>Operating mode</span><strong>SIMULATION</strong></article><article><WalletCards /><span>Designated capital</span><strong>{money(capital)}</strong></article><article><Bot /><span>Strategies</span><strong>3 enabled</strong></article><article><ShieldCheck /><span>Safety gates</span><strong>ENFORCED</strong></article></div><div className="allocation-review">{status.strategies.map((strategy) => <div key={strategy.id}><span>{strategy.name}</span><b>{money(allocations[strategy.id] ?? 0)}</b></div>)}</div></div>}
        {error && <div className="form-error">{error}</div>}
      </div>
      <footer><button className="button secondary" disabled={step === 0 || busy} onClick={() => setStep(step - 1)}><ChevronLeft size={16} /> Back</button>{step < steps.length - 1 ? <button className="button primary" disabled={!valid} onClick={() => setStep(step + 1)}>Continue <ChevronRight size={16} /></button> : <button className="button primary" disabled={busy} onClick={() => void finish()}>{busy ? 'Commissioning…' : 'Finish setup'} <Check size={16} /></button>}</footer>
    </section>
  </main>;
}

export function LoginScreen({ onAuthenticated }: { onAuthenticated: (csrf: string) => void }) {
  const [username, setUsername] = useState('operator'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const login = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await post<{ csrf: string }>('/api/auth/login', { username, password }); onAuthenticated(result.csrf); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); setBusy(false); } };
  return <main className="login-shell"><section className="login-brand"><div className="large-mark">A</div><p className="eyebrow">AGENTIC TRADING MANAGER</p><h1>The guarded layer between intelligence and capital.</h1><p>Local-first · simulation-first · operator controlled</p></section><form className="login-card" onSubmit={(event) => void login(event)}><div className="login-icon"><LockKeyhole /></div><p className="eyebrow">CONTROL ROOM ACCESS</p><h2>Welcome back.</h2><label className="field"><span>Username</span><input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" autoFocus /></label><label className="field"><span>Password</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></label>{error && <div className="form-error">{error}</div>}<button className="button primary wide" disabled={busy}>{busy ? 'Authenticating…' : 'Enter control room'}</button><p className="login-foot">Protected local session · SameSite cookie · CSRF enforcement</p></form></main>;
}

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
