import {useState} from 'react';
import {post} from '../api';
import {RESEARCH_REQUIRED,type ProposalInput,type Proposal} from '../../packages/trading-v2/src/model';
const names={SAFE_LONG_TERM:'Safe',AGGRESSIVE_STOCKS:'Aggressive',OPTIONS:'Options'};
export function ProposalForm({create,notify}:{create:(body:ProposalInput)=>Promise<void>;notify:(message:string,tone?:string)=>void}){
  const [asset,setAsset]=useState<'EQUITY'|'ETF'|'OPTION'>('EQUITY'),[strategy,setStrategy]=useState<ProposalInput['strategy']>('AGGRESSIVE_STOCKS'),[symbol,setSymbol]=useState(''),[side,setSide]=useState<'BUY'|'SELL'>('BUY'),[quantity,setQuantity]=useState(''),[price,setPrice]=useState(''),[orderType,setOrderType]=useState<'LIMIT'|'MARKET'>('LIMIT'),[thesis,setThesis]=useState(''),[risk,setRisk]=useState(''),[exit,setExit]=useState(''),[catalyst,setCatalyst]=useState(''),[holdingDays,setHoldingDays]=useState('5'),[optionStrategy,setOptionStrategy]=useState<'LONG_CALL'|'LONG_PUT'|'COVERED_CALL'|'CASH_SECURED_PUT'>('LONG_CALL'),[strike,setStrike]=useState(''),[expiry,setExpiry]=useState(''),[optionId,setOptionId]=useState(''),[busy,setBusy]=useState(false),[source,setSource]=useState(''),[classificationReview,setClassificationReview]=useState('');
  const optionType=optionStrategy.includes('CALL')?'CALL':'PUT';
  const submit=async()=>{setBusy(true);try{const now=new Date(),q=Number(quantity),limit=orderType==='LIMIT'?Number(price):null;
    await create({schemaVersion:2,strategy:asset==='OPTION'?'OPTIONS':strategy,assetClass:asset,symbol:symbol.trim().toUpperCase(),underlying:asset==='OPTION'?symbol.trim().toUpperCase():null,side,positionEffect:asset==='OPTION'?(optionStrategy.startsWith('LONG')?(side==='BUY'?'OPEN':'CLOSE'):(side==='SELL'?'OPEN':'CLOSE')):side==='BUY'?'OPEN':'CLOSE',quantity:q,dollarAmount:null,orderType:asset==='OPTION'?'LIMIT':orderType,limitPrice:asset==='OPTION'?Number(price):limit,stopPrice:null,timeInForce:'DAY',marketHours:'REGULAR',createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+900000).toISOString(),option:asset==='OPTION'?{optionId,type:optionType,strike:Number(strike),expiration:expiry,contracts:q,strategy:optionStrategy,maxLoss:optionStrategy==='CASH_SECURED_PUT'?Number(strike)*100*q:Number(price)*100*q,collateralRequired:optionStrategy==='CASH_SECURED_PUT'?Number(strike)*100*q:0,estimatedPremium:Number(price)*100*q}:null,researchSummary:thesis,thesis,catalyst,technicalSetup:'Pending source-grounded research',fundamentalContext:'Pending source-grounded research',riskFactors:[risk],invalidation:risk,expectedHoldingPeriod:holdingDays+' trading days',holdingTradingDays:Number(holdingDays),exitPlan:exit});
  }catch(e){notify(String(e),'danger');}finally{setBusy(false);}};
  return <details className="product-card" open><summary>Create a trade proposal</summary><p>A draft cannot place an order. Research, risk, broker review, approval, and submission are separate steps.</p><div className="opening-cash"><label className="field"><span>Asset</span><select value={asset} onChange={e=>setAsset(e.target.value as typeof asset)}><option value="EQUITY">Stock</option><option value="ETF">ETF</option><option value="OPTION">Level 2 option</option></select></label><label className="field"><span>Strategy</span><select disabled={asset==='OPTION'} value={asset==='OPTION'?'OPTIONS':strategy} onChange={e=>setStrategy(e.target.value as typeof strategy)}>{Object.entries(names).filter(([s])=>s!=='OPTIONS'||asset==='OPTION').map(([s,n])=><option key={s} value={s}>{n}</option>)}</select></label><label className="field"><span>{asset==='OPTION'?'Underlying symbol':'Symbol'}</span><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><label className="field"><span>Buy / sell</span><select value={side} onChange={e=>setSide(e.target.value as typeof side)}><option>BUY</option><option>SELL</option></select></label><label className="field"><span>{asset==='OPTION'?'Contracts':'Shares'}</span><input type="number" min="0" step={asset==='OPTION'?'1':'any'} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="field"><span>Order type</span><select disabled={asset==='OPTION'} value={asset==='OPTION'?'LIMIT':orderType} onChange={e=>setOrderType(e.target.value as typeof orderType)}><option>LIMIT</option><option>MARKET</option></select></label>{(orderType==='LIMIT'||asset==='OPTION')&&<label className="field"><span>Limit price {asset==='OPTION'?'per share of premium':''}</span><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label>}<label className="field"><span>Holding plan (trading days)</span><input type="number" min="0" value={holdingDays} onChange={e=>setHoldingDays(e.target.value)}/></label></div>
    {asset==='OPTION'&&<div className="opening-cash"><label className="field"><span>Option strategy</span><select value={optionStrategy} onChange={e=>setOptionStrategy(e.target.value as typeof optionStrategy)}>{['LONG_CALL','LONG_PUT','COVERED_CALL','CASH_SECURED_PUT'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Strike</span><input type="number" min="0" value={strike} onChange={e=>setStrike(e.target.value)}/></label><label className="field"><span>Expiration</span><input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label className="field"><span>Official contract ID</span><input value={optionId} onChange={e=>setOptionId(e.target.value)}/></label><button className="button secondary" disabled={!symbol||!expiry||!strike} onClick={()=>void post<{structuredContent:{data:{instruments:Array<{id:string;chain_symbol:string;strike_price:string;expiration_date:string;type:string}>}}}>('/api/v2/connections/robinhood/read',{tool:'get_option_instruments',arguments:{chain_symbol:symbol,expiration_dates:expiry,strike_price:strike,type:optionType.toLowerCase(),state:'active',tradability:'tradable'}}).then(r=>{const rows=r.structuredContent.data.instruments;if(rows.length!==1)throw new Error('Choose exact unique broker contract; '+rows.length+' results');setOptionId(rows[0]!.id);notify('Official contract selected.');}).catch(e=>notify(String(e),'danger'))}>Find exact Robinhood contract</button></div>}
    <label className="field"><span>Thesis</span><textarea value={thesis} onChange={e=>setThesis(e.target.value)}/></label><label className="field"><span>Risk and invalidation</span><textarea value={risk} onChange={e=>setRisk(e.target.value)}/></label><label className="field"><span>Catalyst</span><input value={catalyst} onChange={e=>setCatalyst(e.target.value)}/></label><label className="field"><span>Exit plan</span><textarea value={exit} onChange={e=>setExit(e.target.value)}/></label><p>Estimated limit notional: {price&&quantity?'$'+(Number(price)*Number(quantity)*(asset==='OPTION'?100:1)).toFixed(2):'Unavailable'}. Risk checks determine capital and collateral; proposed estimates never authorize execution.</p><button className="button primary" disabled={busy||!symbol||!quantity||!thesis||!risk||!exit||asset==='OPTION'&&!optionId} onClick={()=>void submit()}>Create draft for review</button>
    <details><summary>Verify security classification</summary><p>The official quote contract omits leverage and stock/ETF classification. Review a reliable listing or issuer source before the risk engine can accept this security or option underlying.</p><label className="field"><span>Listing / issuer source URL</span><input type="url" value={source} onChange={e=>setSource(e.target.value)}/></label><label className="field"><span>Classification review</span><textarea value={classificationReview} onChange={e=>setClassificationReview(e.target.value)}/></label><button className="button secondary" disabled={!symbol||!source||classificationReview.length<20} onClick={()=>{if(window.confirm('Confirm this is a US-listed, unleveraged '+(asset==='ETF'?'ETF':'stock')+' based on your source review?'))void post('/api/v2/instrument-review',{symbol,assetClass:asset==='ETF'?'ETF':'EQUITY',source,review:classificationReview,confirmation:'VERIFY US LISTED UNLEVERAGED SECURITY'}).then(()=>notify('Classification reviewed and audited.')).catch(e=>notify(String(e),'danger'));}}>Confirm reviewed classification</button></details>
  </details>;
}
export function ResearchForm({proposal,attach}:{proposal:Proposal;attach:(body:unknown)=>Promise<void>}){
  const [items,setItems]=useState<Record<string,{summary:string;source:string}>>({});
  return <details><summary>Attach source-grounded research</summary><p>Complete every required category. Only sources actually reviewed should be recorded.</p>{RESEARCH_REQUIRED[proposal.strategy].map(category=><div key={category}><label className="field"><span>{category.replaceAll('_',' ')}</span><textarea value={items[category]?.summary??''} onChange={e=>setItems({...items,[category]:{source:items[category]?.source??'',summary:e.target.value}})}/></label><label className="field"><span>Source URL</span><input type="url" value={items[category]?.source??''} onChange={e=>setItems({...items,[category]:{summary:items[category]?.summary??'',source:e.target.value}})}/></label></div>)}<button className="button primary" disabled={!RESEARCH_REQUIRED[proposal.strategy].every(c=>items[c]&&items[c]!.summary.length>=20&&items[c]!.source.startsWith('https://'))} onClick={()=>void attach({simulated:false,items:RESEARCH_REQUIRED[proposal.strategy].map(category=>({category,summary:items[category]!.summary,sources:[items[category]!.source],observedAt:new Date().toISOString()}))})}>Save reviewed research</button></details>;
}
