import {useEffect,useState} from 'react';
import {api,post} from '../api';
type State={version:number;config:{symbols:Record<string,Record<string,unknown>>;global:Record<string,unknown>};descriptors:Array<{key:string;explanation:string;default:unknown;validRange:unknown}>};
export function SymbolRiskOverrides({notify}:{notify:(message:string,tone?:string)=>void}){
  const [state,setState]=useState<State|null>(null),[symbol,setSymbol]=useState(''),[key,setKey]=useState('blockedSymbols'),[value,setValue]=useState('[]'),[preview,setPreview]=useState<{config:State['config'];expectedVersion:number}|null>(null),[reason,setReason]=useState(''),[password,setPassword]=useState('');
  const load=async()=>setState(await api<State>('/api/v2/risk-configuration'));useEffect(()=>{void load();},[]);
  const review=async(remove=false)=>{if(!state)return;try{const config=structuredClone(state.config);config.symbols[symbol]={...config.symbols[symbol]};if(remove)delete config.symbols[symbol]![key];else config.symbols[symbol]![key]=JSON.parse(value);setPreview(await post('/api/v2/risk-configuration/preview',config));}catch(e){notify(String(e),'danger');}};
  const apply=async()=>{if(!preview)return;try{await post('/api/v2/reauth',{password});setPassword('');await post('/api/v2/risk-configuration/apply',{config:preview.config,expectedVersion:preview.expectedVersion,reason,confirmation:'APPLY RISK CONFIGURATION'});setPreview(null);await load();notify('Symbol risk override saved; rerun simulation.');}catch(e){notify(String(e),'danger');}};
  const descriptor=state?.descriptors.find(d=>d.key===key);
  return <section className="panel terminal-panel"><h2>Advanced symbol-specific overrides</h2><p className="muted">A symbol override is applied last, after global, sleeve and asset-class settings. The same typed validation, version guard, confirmation and audit service is used. Removing an override restores inheritance.</p><div className="terminal-toolbar"><label>Symbol<input value={symbol} onChange={e=>{setSymbol(e.target.value.toUpperCase());setPreview(null);}} placeholder="TSLA"/></label><label>Parameter<select value={key} onChange={e=>{setKey(e.target.value);setValue(JSON.stringify(state?.config.symbols[symbol]?.[e.target.value]??state?.config.global[e.target.value]));setPreview(null);}}>{state?.descriptors.map(d=><option key={d.key}>{d.key}</option>)}</select></label></div><p>{descriptor?.explanation}</p><small>Current override: {JSON.stringify(state?.config.symbols[symbol]?.[key]??'INHERITED')} · Default: {JSON.stringify(descriptor?.default)} · Range: {JSON.stringify(descriptor?.validRange)}</small><label>Typed JSON value<input value={value} onChange={e=>{setValue(e.target.value);setPreview(null);}}/></label><div className="terminal-toolbar"><button disabled={!/^[A-Z][A-Z0-9.-]{0,9}$/.test(symbol)} onClick={()=>void review()}>Validate / preview override</button><button disabled={!Object.hasOwn(state?.config.symbols[symbol]??{},key)} onClick={()=>void review(true)}>Preview restore inheritance</button></div>{preview&&<><pre className="terminal-json">{JSON.stringify(preview,null,2)}</pre><label>Review / reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Reauthenticate<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={reason.length<20||!password} onClick={()=>void apply()}>Confirm reviewed symbol change</button></>}</section>;
}
