import {useCallback,useEffect,useState} from 'react';
import {api,post} from '../api';
import type {Sleeve,Proposal} from '../../packages/trading-v2/src/model';
type RecordRow=Record<string,unknown>;
export interface State {account:{netAccountValue:number;buyingPower:number;cash:number;asOf:string;positions?:Array<{symbol:string;quantity:number;averageCost:number;price:number}>}|null;sleeves:Array<{strategy:Sleeve;cash:number;enabled:boolean;target:number;currentEquity:number;startingCapital:number;weeklyStartingCapital:number;highWaterMark:number;realizedPnL:number;unrealizedPnL:number;drawdown:number;capitalAtRisk:number;reservedCapital:number;availableCapital:number;killed:boolean;killReason:string|null;openOrders:number;positions:unknown[];options:unknown[];policy:RecordRow}>;readiness:{version:string;schemaVersion:number;gitSha:string;uptime:number;ready:boolean;checks:Record<string,boolean>;limitation:string};globalPause:boolean;stopped:boolean;maintenance:boolean;reconciliation:string[];policy:RecordRow}
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const labels={proposals:'Proposals',risk:'Risk Decisions',pending:'Pending Execution',orders:'Orders',fills:'Fills',positions:'Positions',options:'Options',ledger:'Strategy Ledger',assignments:'Ownership',audit:'Audit Log',reports:'Reports',scheduler:'Scheduler',policies:'Sleeve Policies',health:'Health / Settings'};
type Tab=keyof typeof labels;
function value(v:unknown){return v===null?'—':typeof v==='object'?JSON.stringify(v):String(v);}
export function ResourceTable({rows}:{rows:RecordRow[]}){
  const keys=[...new Set(rows.slice(0,10).flatMap(r=>Object.keys(r)))].filter(k=>!k.endsWith('_json')).slice(0,8);
  if(!rows.length)return <p className="empty-state">Nothing recorded here yet. Activity will appear after a simulation, account sync, or relevant action.</p>;
  return <div className="v2-table"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}<th>Details</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{keys.map(k=><td key={k}>{value(r[k])}</td>)}<td><details><summary>Inspect</summary><pre>{JSON.stringify(r,null,2)}</pre></details></td></tr>)}</tbody></table></div>;
}
export function TradingWorkspace({notify}:{notify:(message:string,tone?:string)=>void}){
  const [state,setState]=useState<State|null>(null),[tab,setTab]=useState<Tab>('proposals'),[rows,setRows]=useState<RecordRow[]>([]),[detail,setDetail]=useState<RecordRow|null>(null),[input,setInput]=useState(''),[kind,setKind]=useState<'proposal'|'research'>('proposal'),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{setState(await api<State>('/api/v2/state'));if(!['health','policies'].includes(tab))setRows(await api<RecordRow[]>(tab==='proposals'?'/api/v2/proposals':tab==='scheduler'?'/api/v2/scheduler':'/api/v2/resources/'+tab));}catch(e){notify(e instanceof Error?e.message:String(e),'danger');}},[tab,notify]);
  useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15000);return()=>clearInterval(t);},[load]);
  const action=async(path:string,body:unknown={})=>{setBusy(true);try{const result=await post<RecordRow>(path,body);if(path.includes('/proposals/')&&!path.endsWith('/approve'))setDetail(result);notify('Application action recorded.');await load();}catch(e){notify(e instanceof Error?e.message:String(e),'danger');}finally{setBusy(false);}};
  const p=detail?.proposal as Proposal|undefined;
  if(!state)return <p>Loading trading workspace…</p>;
  return <section className="v2-workspace">
    <div className="section-heading"><div><p className="eyebrow">REVIEW BEFORE ACTING</p><h2>Trades & activity</h2></div><button className="button secondary" onClick={()=>void load()}>Refresh</button></div>
    <details className="panel product-card"><summary>Account and strategy details</summary><div className="v2-metrics">{[['Net account value',state.account?.netAccountValue],['Buying power',state.account?.buyingPower],['Cash',state.account?.cash]].map(([label,n])=><article className="panel" key={label}><small>{label}</small><h2>{typeof n==='number'?money(n):'Unverified'}</h2></article>)}
      <article className="panel"><small>Controls</small><p>{state.stopped?'STOPPED':state.maintenance?'MAINTENANCE':state.globalPause?'PAUSED':'MONITORING'}</p><small>Reconciliation: {state.reconciliation.length?'REQUIRED':'clear'} · LIVE readiness: {state.readiness.ready?'ready':'blocked'}</small></article></div>
    <div className="v2-sleeves">{state.sleeves.map(s=><article className="panel" key={s.strategy}><div className="section-heading"><h3>{s.strategy.replaceAll('_',' ')}</h3><span className={s.killed?'negative':''}>{s.killed?'KILLED':s.enabled?'ENABLED':'PAUSED'}</span></div><dl>{[['Weekly target',s.target],['Actual equity',s.currentEquity],['Initial capital',s.startingCapital],['Weekly baseline',s.weeklyStartingCapital],['High water',s.highWaterMark],['Realized P&L',s.realizedPnL],['Unrealized P&L',s.unrealizedPnL],['Capital at risk',s.capitalAtRisk],['Reserved',s.reservedCapital],['Available',s.availableCapital]].map(([label,n])=><div key={label}><dt>{label}</dt><dd className={String(label).includes('P&L')?(Number(n)>=0?'positive':'negative'):''}>{money(Number(n))}</dd></div>)}</dl><p>Drawdown {s.drawdown.toFixed(2)}% · {s.positions.length+s.options.length} positions · {s.openOrders} open orders</p><small>{String(s.policy.executionPolicy)} · 60% emergency kill</small>{s.killReason&&<p className="negative">{s.killReason}</p>}</article>)}</div>
    </details><nav className="v2-tabs" aria-label="Trading records">{Object.entries(labels).map(([id,label])=><button key={id} className={'button '+(tab===id?'primary':'secondary')} onClick={()=>{setTab(id as Tab);setDetail(null);}}>{label}</button>)}</nav>
    <article className="panel">
      <div className="section-heading"><h2>{labels[tab]}</h2>{tab==='reports'&&<div><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/reports',{kind:'DAILY_REPORT'})}>Daily</button><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/reports',{kind:'WEEKLY_REPORT'})}>Weekly</button></div>}</div>
      {tab==='policies'?<PolicyEditor state={state} action={action} notify={notify}/>:tab==='health'?<><p>{state.readiness.limitation}</p><p>v{state.readiness.version} · schema {state.readiness.schemaVersion} · {state.readiness.gitSha} · uptime {state.readiness.uptime}s</p><ResourceTable rows={Object.entries(state.readiness.checks).map(([check,passed])=>({check,passed}))}/><h3>Account risk policy</h3><pre>{JSON.stringify(state.policy,null,2)}</pre><div className="v2-actions"><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/reconciliation')}>Reconcile</button><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/allocation',{confirmation:'RECOMPUTE WEEKLY ALLOCATION'})}>Recompute weekly targets</button><button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/self-tests')}>Run isolated simulation self-tests</button></div></>:
      tab==='proposals'?<>{!rows.length&&<div className="useful-empty"><h3>No trades waiting for review.</h3><p>The assistant can research an idea and draft a proposal. It must pass risk checks before you can approve it.</p></div>}<div className="v2-proposal-list">{rows.map(r=><button key={String(r.id)} className="button secondary" onClick={()=>void api<RecordRow>('/api/v2/proposals/'+r.id).then(setDetail).catch(e=>notify(String(e),'danger'))}>{String(r.symbol)} · {String(r.strategy)} · v{String(r.version)} · {String(r.state)}</button>)}</div>
        {p&&<section className="v2-detail"><h3>{p.symbol} / {p.state} / version {p.version}</h3><div className="terminal-stats"><span>Action<strong>{p.side} {p.quantity} {p.assetClass==='OPTION'?'contracts':'shares'}</strong></span><span>Order type<strong>{p.orderType}</strong></span><span>Strategy<strong>{p.strategy.replaceAll('_',' ')}</strong></span></div><p>{p.thesis}</p><p>Invalidation: {p.invalidation}</p><p>Exit plan: {p.exitPlan}</p><details><summary>Order, preview & risk evidence</summary><h4>Requested order</h4><pre>{JSON.stringify(p,null,2)}</pre><h4>Research and broker preview</h4><pre>{JSON.stringify({research:detail?.research,preview:detail?.preview,approval:detail?.approval},null,2)}</pre><h4>Risk decisions</h4><ResourceTable rows={(detail?.risk??[]) as RecordRow[]}/><h4>Lifecycle history</h4><ResourceTable rows={(detail?.transitions??[]) as RecordRow[]}/><h4>Execution</h4><pre>{JSON.stringify(detail?.execution,null,2)}</pre></details><div className="v2-actions">
          {['RESEARCHED','RISK_REJECTED'].includes(p.state)&&<button className="button primary" disabled={busy} onClick={()=>void action('/api/v2/proposals/'+p.id+'/review')}>Risk review + preview</button>}
          {p.state==='READY_TO_EXECUTE'&&<><button className="button secondary" disabled={busy} onClick={()=>{if(window.confirm('Approve exactly this proposal version and broker preview?'))void action('/api/v2/proposals/'+p.id+'/approve',{version:p.version,confirmation:'APPROVE EXECUTION'});}}>Approve this version</button><button className="button primary" disabled={busy} onClick={()=>{if(window.confirm('Request execution through second risk check?'))void action('/api/v2/proposals/'+p.id+'/execute');}}>Request execution</button></>}
          {!['FILLED','CLOSED','CANCELLED','REJECTED','EXECUTION_SENT','RECONCILIATION_REQUIRED'].includes(p.state)&&<button className="button secondary" disabled={busy} onClick={()=>void action('/api/v2/proposals/'+p.id+'/cancel')}>Cancel</button>}
        </div></section>}
        <details><summary>Structured proposal / research input</summary><p>Paste a version-2 proposal or a complete source-grounded research checklist. Missing fields are rejected, not invented. Simulation options need an operator fixture.</p><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="proposal">Create proposal</option><option value="research">Attach research to selected DRAFT</option></select><textarea className="v2-json" value={input} onChange={e=>setInput(e.target.value)} placeholder="Strict JSON input"/><button className="button primary" disabled={busy||!input||(kind==='research'&&!p)} onClick={()=>{try{void action(kind==='proposal'?'/api/v2/proposals':'/api/v2/proposals/'+p!.id+'/research',JSON.parse(input));}catch{notify('Invalid JSON','danger');}}}>Submit structured input</button></details>
      </>:tab==='scheduler'?<>{rows.map(r=><details key={String(r.id)}><summary>{String(r.id)} · {String(r.cron)} · {String(r.timezone)}</summary><pre>{JSON.stringify(r,null,2)}</pre><button className="button secondary" onClick={()=>{const cron=window.prompt('Five-field cron in America/Los_Angeles',String(r.cron));if(cron)void action('/api/v2/scheduler/'+r.id,{cron,enabled:true});}}>Edit schedule</button><button className="button secondary" onClick={()=>void action('/api/v2/scheduler/'+r.id,{cron:r.cron,enabled:!r.enabled})}>{r.enabled?'Disable':'Enable'}</button></details>)}</>:<ResourceTable rows={rows}/>}
    </article>
  </section>;
}
function PolicyEditor({state,action,notify}:{state:State;action:(path:string,body?:unknown)=>Promise<void>;notify:(message:string,tone?:string)=>void}){
  const [selected,setSelected]=useState<Sleeve>('SAFE_LONG_TERM'),[policy,setPolicy]=useState(JSON.stringify(state.sleeves[0]!.policy,null,2)),[review,setReview]=useState(''),[confirmation,setConfirmation]=useState('');
  return <section><p>Policies are independent for SAFE, AGGRESSIVE, and OPTIONS. Enabling autonomous risk-approved execution does not enable LIVE, release STOP, or generate orders on a schedule.</p>
    <select aria-label="Sleeve" value={selected} onChange={e=>{const s=e.target.value as Sleeve;setSelected(s);setPolicy(JSON.stringify(state.sleeves.find(x=>x.strategy===s)!.policy,null,2));setConfirmation('');}}>{state.sleeves.map(s=><option key={s.strategy}>{s.strategy}</option>)}</select>
    <textarea className="v2-json" aria-label="Sleeve policy JSON" value={policy} onChange={e=>setPolicy(e.target.value)}/>
    <input aria-label="Policy review" placeholder="Explicit risk review (20+ characters)" value={review} onChange={e=>setReview(e.target.value)}/>
    <input aria-label="Confirmation phrase" placeholder={'UPDATE '+selected+' POLICY'} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/>
    <button className="button primary" onClick={()=>{try{void action('/api/v2/sleeves/'+selected+'/policy',{policy:JSON.parse(policy),review,confirmation});}catch{notify('Invalid policy JSON','danger');}}}>Apply this sleeve policy</button>
    <h3>Explicit weekly kill reset</h3><p>Reset never resumes trading. Requires a weekly review and exact RESET sleeve phrase.</p><button className="button secondary" onClick={()=>void action('/api/v2/sleeves/'+selected+'/reset',{confirmation:window.prompt('Type RESET '+selected)??'',review})}>Review / reset selected sleeve</button>
    <h3>Upgrade and STOP review</h3><button className="button secondary" onClick={()=>{if(window.confirm('Accept the currently displayed migrated ownership after fresh reconciliation?'))void action('/api/v2/upgrade-review',{confirmation:'ACCEPT MIGRATED OWNERSHIP',review});}}>Accept migrated ownership</button><button className="button secondary" onClick={()=>{if(window.confirm('Release STOP? Global pause and LIVE revocation remain in effect.'))void action('/api/v2/stop-release',{confirmation:'RELEASE STOP',review});}}>Release STOP latch</button>
  </section>;
}
