import {z} from 'zod';
import type {AppDatabase} from '../../database/src/database.js';
import {nowIso} from '../../core/src/utils.js';
import {configurationEvidenceHash} from './configuration.js';
import type {ProposalService} from './proposals.js';
export const previewEvidenceRequest=z.object({proposalId:z.string().min(1),expectedVersion:z.number().int().positive(),confirmation:z.literal('VERIFY MANUAL BROKER PREVIEW'),review:z.string().min(20).max(2000)}).strict();
type Evidence={proposalId:string;version:number;accountId:string;orderHash:string;catalogHash:string;configurationHash:string;actor:string;review:string;at:string};
export function hasVerifiedPreview(db:AppDatabase){const e=db.getSetting<Evidence|null>('manual_preview_evidence',null),a=db.getSetting<{accountId:string;complete:boolean;healthy:boolean;asOf:string}|null>('broker_account_v2',null);if(!e||db.getMode()!=='READ_ONLY'||e.accountId!==process.env.ROBINHOOD_AGENTIC_ACCOUNT_ID||!a?.complete||!a.healthy||a.accountId!==e.accountId||Date.now()-Date.parse(a.asOf)>120000||Date.parse(a.asOf)>Date.now()+5000||Date.now()-Date.parse(e.at)>900000||Date.parse(e.at)>Date.now()+5000||e.configurationHash!==configurationEvidenceHash(db)||e.catalogHash!==db.getSetting('official_mcp_catalog_hash',''))return false;const p=db.raw.prepare('SELECT version,preview_hash,state FROM proposals WHERE id=?').get(e.proposalId) as {version:number;preview_hash:string;state:string}|undefined;return !!p&&p.version===e.version&&p.preview_hash===e.orderHash&&p.state==='READY_TO_EXECUTE';}
export function verifyManualPreview(service:ProposalService,input:unknown,actor:string){
  const b=previewEvidenceRequest.parse(input),db=service.db,p=service.get(b.proposalId),row=service.row(p.id),preview=JSON.parse(row.preview_json??'null') as {approved:boolean;asOf:string}|null,a=db.getSetting<{accountId:string;complete:boolean;healthy:boolean;asOf:string}|null>('broker_account_v2',null),catalog=db.getSetting<string>('official_mcp_catalog_hash','');
  const latest=db.raw.prepare('SELECT approved,facts_json,created_at FROM risk_decisions_v2 WHERE proposal_id=? AND version=? ORDER BY rowid DESC LIMIT 1').get(p.id,p.version) as {approved:number;facts_json:string;created_at:string}|undefined;
  const facts=latest?JSON.parse(latest.facts_json) as {account:{accountId:string;complete:boolean;healthy:boolean;asOf:string};q:{provenance?:string;tradingEligible:boolean};orderHash:string}:null;
  if(!facts||facts.account.accountId!==a?.accountId||!facts.account.complete||!facts.account.healthy||Date.now()-Date.parse(facts.account.asOf)>60000||facts.q.provenance!=='OFFICIAL_MCP_REVIEWED_BINDING'||!facts.q.tradingEligible)throw new Error('Manual preview evidence requires verified official broker facts, not Simulation or manually substituted cached account values');
  if(db.getMode()!=='READ_ONLY'||p.version!==b.expectedVersion||p.state!=='READY_TO_EXECUTE'||Date.parse(p.expiresAt)<=Date.now()||!preview?.approved||Date.now()-Date.parse(preview.asOf)>60000||Date.parse(preview.asOf)>Date.now()+5000||!row.preview_hash||!latest?.approved||JSON.parse(latest.facts_json).orderHash!==row.preview_hash||Date.now()-Date.parse(latest.created_at)>60000||!catalog||!a?.complete||!a.healthy||a.accountId!==process.env.ROBINHOOD_AGENTIC_ACCOUNT_ID||Date.now()-Date.parse(a.asOf)>60000||Date.parse(a.asOf)>Date.now()+5000||!db.getSetting('reconciliation_clear',false))throw new Error('Requires current real-account READ_ONLY reconciliation and a fresh approved broker preview for this exact proposal version/hash');
  const evidence:Evidence={proposalId:p.id,version:p.version,accountId:a.accountId,orderHash:row.preview_hash,catalogHash:catalog,configurationHash:configurationEvidenceHash(db),actor,review:b.review,at:nowIso()};db.setSetting('manual_preview_evidence',evidence);db.audit(actor,'VERIFIED_MANUAL_BROKER_PREVIEW','proposal',p.id,evidence);return {evidence,ordersPlaced:0,liveEnabled:false};
}
