import {z} from 'zod';
import {existsSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import type {TradingBroker,TradingAccount,TrustedQuote,ExecutableOrder,ProposalInput} from './model.js';
import type {OfficialRobinhoodConnection} from './connectors.js';
const money=z.number().finite(),quantity=z.number().finite().nonnegative();
export const normalizedAccountSchema=z.object({accountId:z.string().min(1),agentic:z.boolean(),cash:money,buyingPower:money,netAccountValue:money,optionsLevel:z.number().int(),asOf:z.string().datetime(),healthy:z.boolean(),complete:z.boolean(),positions:z.array(z.object({symbol:z.string(),quantity,averageCost:money.nonnegative(),price:money.positive(),assetClass:z.enum(['EQUITY','ETF'])})),options:z.array(z.object({optionId:z.string(),contracts:z.number().int(),averagePremium:money.nonnegative(),price:money.nonnegative(),collateral:money.nonnegative()})),orders:z.array(z.object({id:z.string(),clientOrderId:z.string().nullable(),status:z.string(),filledQuantity:quantity})),fills:z.array(z.object({id:z.string(),brokerOrderId:z.string(),quantity:quantity.positive(),price:money.positive(),fees:money.nonnegative(),executedAt:z.string().datetime()}))}).strict();
const instrument=z.object({optionId:z.string(),underlying:z.string(),type:z.enum(['CALL','PUT']),strike:money.positive(),expiration:z.string(),multiplier:z.literal(100)});
export const normalizedQuoteSchema=z.object({symbol:z.string(),price:money.positive(),bid:money.positive(),ask:money.positive(),volume:quantity,asOf:z.string().datetime(),tradingEligible:z.boolean(),option:instrument.optional(),usListed:z.boolean().optional(),leveraged:z.boolean().optional(),assetClass:z.enum(['EQUITY','ETF','OPTION']).optional(),sector:z.string().optional(),marketCap:money.nonnegative().optional(),relativeVolume:money.nonnegative().optional(),atrPercent:money.nonnegative().optional(),valuationPE:money.optional(),setupScore:money.optional(),earningsWithinHolding:z.boolean().optional(),openInterest:quantity.optional(),delta:money.optional(),gamma:money.optional(),theta:money.optional(),vega:money.optional(),iv:money.nonnegative().optional(),underlyingPrice:money.positive().optional(),underlyingVolume:quantity.optional(),provenance:z.string().optional()}).strict();
const operation=z.object({calls:z.array(z.object({alias:z.string().regex(/^[a-zA-Z]+$/),tool:z.string(),arguments:z.record(z.string(),z.unknown())}).strict()).min(1).max(20),result:z.unknown()}).strict();
export const mcpBindingSchema=z.object({schemaVersion:z.literal(1),accountId:z.string().min(1),catalogHash:z.string().length(64),verifiedBy:z.string().min(1),reviewReference:z.string().min(20),account:operation,equityQuote:operation,optionQuote:operation,equityPreview:operation,optionPreview:operation}).strict();
export const catalogHash=(catalog:ReturnType<OfficialRobinhoodConnection['catalog']>)=>createHash('sha256').update(JSON.stringify(catalog.map(t=>({name:t.name,inputSchema:t.inputSchema,outputSchema:t.outputSchema})).sort((a,b)=>a.name.localeCompare(b.name)))).digest('hex');
/** Explicit JSON-pointer mapping, reviewed against authenticated schemas. No guessed field aliases or model normalization. */
export function mapContract(template:unknown,sources:Record<string,unknown>):unknown{
  if(Array.isArray(template))return template.map(t=>mapContract(t,sources));if(template===null||typeof template!=='object')return template;
  const t=template as Record<string,unknown>;
  const get=(ref:unknown)=>{if(typeof ref!=='string')throw new Error('Mapping reference invalid');const [alias,path]=ref.split('#');let value=sources[alias??''];if(path)for(const key of path.split('/').slice(1)){const safe=key.replaceAll('~1','/').replaceAll('~0','~');if(['__proto__','constructor','prototype'].includes(safe)||!value||typeof value!=='object'||!Object.hasOwn(value,safe))throw new Error('Required broker field missing: '+ref);value=(value as Record<string,unknown>)[safe];}if(value===undefined)throw new Error('Required broker source missing: '+ref);return value;};
  if('$ref' in t){const v=get(t.$ref);if(t.$number===true){const n=typeof v==='number'?v:typeof v==='string'&&v.trim()?Number(v):NaN;if(!Number.isFinite(n))throw new Error('Broker decimal invalid');return n;}return v;}
  if('$each' in t){const values=get(t.$each);if(!Array.isArray(values))throw new Error('Broker collection missing');return values.map(item=>mapContract(t.$map,{...sources,item}));}
  if('$concat' in t){if(!Array.isArray(t.$concat))throw new Error('Concatenation mapping invalid');return t.$concat.flatMap(part=>{const v=mapContract(part,sources);if(!Array.isArray(v))throw new Error('Concatenated broker field must be array');return v;});}
  return Object.fromEntries(Object.entries(t).map(([k,v])=>{if(['__proto__','constructor','prototype'].includes(k))throw new Error('Unsafe mapping key');return [k,mapContract(v,sources)];}));
}
export class VerifiedReadOnlyMcpBroker implements TradingBroker{
  readonly deterministic=true;
  constructor(readonly connection:OfficialRobinhoodConnection,readonly bindingPath=process.env.ROBINHOOD_BINDING_FILE??''){}
  private binding(){if(!this.bindingPath||!existsSync(this.bindingPath))throw new Error('Authenticate official MCP and install a reviewed schema mapping in ROBINHOOD_BINDING_FILE; no contract is guessed');const b=mcpBindingSchema.parse(JSON.parse(readFileSync(this.bindingPath,'utf8')));if(b.accountId!==process.env.ROBINHOOD_AGENTIC_ACCOUNT_ID||b.catalogHash!==catalogHash(this.connection.catalog()))throw new Error('Broker identity/catalog mapping not verified');return b;}
  private async run(op:z.infer<typeof operation>,params:Record<string,unknown>,preview=false){const sources:Record<string,unknown>={params};for(const c of op.calls){const args=mapContract(c.arguments,sources) as Record<string,unknown>;const result=await this.connection.call(c.tool,args,preview) as {structuredContent?:unknown;content?:Array<{type:string;text?:string}>};if(result.structuredContent!==undefined)sources[c.alias]=result.structuredContent;else{const texts=result.content?.filter(c=>c.type==='text');if(texts?.length!==1||!texts[0]?.text)throw new Error('MCP structured JSON result unavailable');sources[c.alias]=JSON.parse(texts[0].text);}}return mapContract(op.result,sources);}
  async account():Promise<TradingAccount>{const b=this.binding(),a=normalizedAccountSchema.parse(await this.run(b.account,{accountId:b.accountId}));if(a.accountId!==b.accountId||!a.agentic||!a.complete||!a.healthy||Date.now()-Date.parse(a.asOf)>60000||Date.parse(a.asOf)>Date.now()+5000)throw new Error('Normalized Agentic account incomplete/wrong scope/stale');this.connection.validateAccount(a.accountId);return a;}
  async quote(p:ProposalInput):Promise<TrustedQuote>{const b=this.binding(),q=normalizedQuoteSchema.parse(await this.run(p.option?b.optionQuote:b.equityQuote,{accountId:b.accountId,symbol:p.symbol,underlying:p.underlying,optionId:p.option?.optionId??null}));if(q.symbol!==p.symbol||q.ask<q.bid)throw new Error('Quote identity/spread invalid');return {...q,provenance:'OFFICIAL_MCP_REVIEWED_BINDING'} as TrustedQuote;}
  async preview(o:ExecutableOrder){const b=this.binding();return z.object({approved:z.boolean(),asOf:z.string().datetime(),estimatedCost:money.nonnegative(),collateralRequired:money.nonnegative(),reason:z.string()}).strict().parse(await this.run(o.option?b.optionPreview:b.equityPreview,{accountId:b.accountId,...o},true));}
  async place(_o:ExecutableOrder):ReturnType<TradingBroker['place']>{throw new Error('DO NOT ENABLE LIVE YET: official placement not commissioned in this pass');}
  async cancel(_id:string):ReturnType<TradingBroker['cancel']>{throw new Error('Real broker cancellation requires final commissioning and explicit operator confirmation');}
}
