import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {openDatabase,type AppDatabase} from '../../database/src/database.js';
import {VirtualPortfolioLedger} from '../../ledger/src/virtual-ledger.js';
import {SimulationMarketDataProvider} from '../../market-data/src/provider.js';
import {makeId,nowIso} from '../../core/src/utils.js';
import {StrategyAllocationManager} from './capital.js';
import {SimulationTradingBroker} from './broker.js';
import {ProposalService} from './proposals.js';
import {PortfolioAnalytics} from './analytics.js';
import {NotificationService} from './notifications.js';
import {BrokerEventService} from './broker-events.js';
import {RiskConfigurationService,configHash,configurationEvidenceHash,configurationEvidenceSnapshot,type RiskConfiguration} from './configuration.js';
import {exampleProposal} from './self-tests.js';
import {PersistentTradingAgent} from './agent.js';
import {PersistedTradingScheduler} from './scheduling.js';
import {RESEARCH_REQUIRED,proposalSchema,SLEEVES,type ProposalInput,type TradingAccount,type TrustedQuote,type ExecutableOrder} from './model.js';

/** This graph has no live adapter, transport, credential or external-data dependency. */
class ScenarioBroker extends SimulationTradingBroker{
  behavior:'FULL'|'REJECT'|'PARTIAL'|'PENDING'|'UNKNOWN'|'TIMEOUT'='FULL';calls=0;
  accountPatch:Partial<TradingAccount>={};quotePatch:Partial<TrustedQuote>={};
  override async account(){return {...await super.account(),...this.accountPatch};}
  override async quote(p:Pick<ProposalInput,'symbol'>&{option:{optionId:string}|null}){return {...await super.quote(p),...this.quotePatch};}
  override async place(o:ExecutableOrder){this.calls++;const q=await this.quote(o),id=makeId('fixture-order');
    if(this.behavior==='TIMEOUT')throw new Error('Synthetic transport timeout');
    if(this.behavior==='REJECT'||this.behavior==='UNKNOWN')return {id,status:this.behavior==='REJECT'?'REJECTED' as const:'UNKNOWN' as const,fills:[]};
    const quantity=this.behavior==='PARTIAL'?o.quantity/2:this.behavior==='PENDING'?0:o.quantity;
    return {id,status:'ACCEPTED' as const,fills:quantity?[{id:id+':fill',brokerOrderId:id,quantity,price:o.side==='BUY'?q.ask:q.bid,fees:0,executedAt:nowIso()}]:[]};
  }
}
function fixture(path=':memory:',config?:RiskConfiguration){
  const db=openDatabase(path),ledger=new VirtualPortfolioLedger(db),allocation=new StrategyAllocationManager(db,ledger),broker=new ScenarioBroker(db,ledger,new SimulationMarketDataProvider()),proposals=new ProposalService(db,ledger,allocation,()=>broker),analytics=new PortfolioAnalytics(db,ledger,allocation),notifications=new NotificationService(db),events=new BrokerEventService(db,ledger,analytics),risk=new RiskConfigurationService(db);
  db.setSetting('global_risk',{...db.getGlobalRisk(),optionsEnabled:true});if(config)risk.apply(config,0,'SIMULATION','Isolated operator configuration snapshot','APPLY RISK CONFIGURATION');
  const option=(type:'LONG_CALL'|'LONG_PUT'|'COVERED_CALL'|'CASH_SECURED_PUT'='LONG_CALL'):ProposalInput=>{
    const optionId='fixture-'+type,expiration=new Date(Date.now()+60*86400000).toISOString().slice(0,10),kind=type.includes('CALL')?'CALL':'PUT';
    db.raw.prepare('INSERT OR REPLACE INTO simulation_option_instruments VALUES(?,?,?)').run(optionId,JSON.stringify({optionId,underlying:'TEST',type:kind,strike:10,expiration,multiplier:100}),1);
    return {...exampleProposal(),strategy:'OPTIONS',assetClass:'OPTION',symbol:'TEST',underlying:'TEST',side:type.startsWith('LONG')?'BUY':'SELL',limitPrice:type.startsWith('LONG')?1.03:.97,option:{optionId,type:kind,strike:10,expiration,contracts:1,strategy:type,maxLoss:0,collateralRequired:0,estimatedPremium:0}};
  };
  const ready=async(input=exampleProposal())=>{await proposals.reconcile();const p=proposals.create(input,'SCENARIO_AGENT');proposals.research(p.id,{simulated:true,items:RESEARCH_REQUIRED[p.strategy].map(category=>({category,summary:'Explicit synthetic scenario research fixture, not current market research.',sources:['https://example.com/synthetic-fixture'],observedAt:nowIso()}))},'SCENARIO_AGENT');await proposals.review(p.id,'SCENARIO_AGENT');return proposals.get(p.id);};
  const fill=async(input=exampleProposal())=>{const p=await ready(input);if(p.state!=='READY_TO_EXECUTE')throw new Error('Scenario risk rejected: '+JSON.stringify((await proposals.risk(p.id)).checks.filter(c=>!c.ok)));proposals.approve(p.id,1,'SIMULATION_OPERATOR');await proposals.execute(p.id,'SIMULATION_OPERATOR');analytics.snapshot('FILL');notifications.emit(p.id,p.option?'OPTION_OPENED':'AGGRESSIVE_OPENED','INFO',{summary:'Synthetic fill',proposalId:p.id});return proposals.get(p.id);};
  return {db,ledger,allocation,broker,proposals,analytics,notifications,events,risk,option,ready,fill};
}
type Fixture=ReturnType<typeof fixture>;
export interface SimulationEvent{sequence:number;scenarioTime:string;kind:string;name:string;passed:boolean|null;detail:unknown;at:string}
export class FullSystemSimulation{
  private active=new Map<string,{speed:number;cancelled:boolean}>();
  constructor(readonly db:AppDatabase,readonly directory:string,readonly publish:(event:SimulationEvent&{runId:string})=>void=()=>{}){
    db.raw.prepare("UPDATE simulation_runs SET status='INTERRUPTED',finished_at=? WHERE status='RUNNING'").run(nowIso());
  }
  list(){return this.db.raw.prepare('SELECT * FROM simulation_runs ORDER BY created_at DESC LIMIT 50').all();}
  get(id:string){const row=this.db.raw.prepare('SELECT * FROM simulation_runs WHERE id=?').get(id) as {id:string;status:string;result_json:string|null;config_json:string}|undefined;if(!row)throw new Error('Simulation run not found');return {...row,result:row.result_json?JSON.parse(row.result_json):null,events:(this.db.raw.prepare('SELECT body_json FROM simulation_events WHERE run_id=? ORDER BY sequence').all(id) as Array<{body_json:string}>).map(r=>JSON.parse(r.body_json))};}
  speed(id:string,speed:number){if(![1,5,20,0].includes(speed))throw new Error('Speed must be 1,5,20 or 0 (MAX)');const control=this.active.get(id);if(control)control.speed=speed;return {speed};}
  cancel(id:string){const control=this.active.get(id);if(control)control.cancelled=true;}
  start(actor:string,speed=5){if(![0,1,5,20].includes(speed))throw new Error('Invalid simulation speed');if(this.active.size)throw new Error('A full-system test is already running');const id=makeId('simulation'),snapshot=new RiskConfigurationService(this.db).current().config,evidenceHash=configurationEvidenceHash(this.db);
    this.db.raw.prepare('INSERT INTO simulation_runs VALUES(?,?,?,?,?,?,?)').run(id,actor,'RUNNING',JSON.stringify(configurationEvidenceSnapshot(this.db)),null,nowIso(),null);const control={speed,cancelled:false};this.active.set(id,control);
    void this.run(id,snapshot,control,evidenceHash).catch(error=>{this.db.raw.prepare("UPDATE simulation_runs SET status='FAILED',result_json=?,finished_at=? WHERE id=?").run(JSON.stringify({ok:false,error:error instanceof Error?error.message:'Simulation error'}),nowIso(),id);this.active.delete(id);});return {id};
  }
  async runNow(actor='CLI'){const {id}=this.start(actor,0);while(this.active.has(id))await new Promise(r=>setTimeout(r,10));return this.get(id);}
  async shutdown(){for(const c of this.active.values()){c.cancelled=true;c.speed=0;}while(this.active.size)await new Promise(r=>setTimeout(r,10));}
  private async run(id:string,config:RiskConfiguration,control:{speed:number;cancelled:boolean},evidenceHash:string){
    const started=Date.now();mkdirSync(this.directory,{recursive:true,mode:0o700});const main=fixture(join(this.directory,id+'.db'),config),assertions:Array<{name:string;passed:boolean;detail:string}>=[];let sequence=0;
    const emit=(kind:string,name:string,passed:boolean|null,detail:unknown)=>{const event:SimulationEvent={sequence:++sequence,scenarioTime:new Date(started+sequence*8*60000).toISOString(),kind,name,passed,detail,at:nowIso()};this.db.raw.prepare('INSERT INTO simulation_events VALUES(?,?,?)').run(id,sequence,JSON.stringify(event));this.publish({...event,runId:id});};
    const check=async(name:string,test:(f:Fixture)=>Promise<boolean>|boolean,useMain=false)=>{if(control.cancelled)return;const f=useMain?main:fixture();let passed=false,detail='';try{passed=await test(f);if(!passed)detail='Assertion returned false';}catch(error){detail=error instanceof Error?error.message:'Scenario exception';}finally{if(!useMain)f.db.close();}assertions.push({name,passed,detail});emit('ASSERTION',name,passed,detail);
      if(useMain){main.analytics.snapshot('SCENARIO_PROGRESS');emit('PORTFOLIO',name,null,{account:await main.broker.account(),sleeves:SLEEVES.map(s=>main.allocation.state(s)),chart:main.analytics.series('ALL'),orders:main.db.raw.prepare('SELECT * FROM orders').all(),fills:main.db.raw.prepare('SELECT * FROM fills').all(),risk:main.db.raw.prepare('SELECT * FROM risk_decisions_v2').all(),notifications:main.notifications.list(),reports:main.db.raw.prepare('SELECT * FROM trading_reports').all()});}
      if(control.speed)await new Promise(r=>setTimeout(r,1500/control.speed));};
    const rejection=async(f:Fixture,p:ProposalInput,code:string)=>{await f.proposals.reconcile();const created=f.proposals.create(p,'SIMULATION');return (await f.proposals.risk(created.id)).checks.some(c=>c.code===code&&!c.ok);};
    const patch=(f:Fixture,key:string,value:unknown)=>{const c=f.risk.current();(c.config.global as unknown as Record<string,unknown>)[key]=value;f.risk.apply(c.config,c.version,'SIMULATION','Synthetic mid-session configuration test','APPLY RISK CONFIGURATION');};
    try{
      emit('STARTUP','Isolated DB load; no external adapters',null,{namespace:id,configHash:configHash(config),broker:'ScenarioBroker',account:'SIMULATION',liveCalls:0});
      await check('Migration and database integrity',f=>f.db.raw.pragma('integrity_check',{simple:true})==='ok',true);
      await check('Account reconciliation',async f=>(await f.proposals.reconcile()).clear,true);
      await check('NAV allocation thirds conserve cash',f=>{const a=f.allocation.weekly(50000,'SIMULATION');return a.length===3&&Math.abs(a.reduce((n,s)=>n+s.target,0)-50000)<.001;},true);
      await check('SAFE researched, risk checked, previewed, approved and filled',async f=>(await f.fill({...exampleProposal(),strategy:'SAFE_LONG_TERM',holdingTradingDays:180})).state==='FILLED',true);
      await check('AGGRESSIVE limit entry full lifecycle',async f=>(await f.fill()).state==='FILLED',true);
      await check('OPTIONS long call full lifecycle',async f=>(await f.fill(f.option())).state==='FILLED',true);
      await check('Equity MARKET fixture uses deterministic pipeline',async f=>(await f.fill({...exampleProposal(),orderType:'MARKET',limitPrice:null})).state==='FILLED');
      await check('Broker rejected order',async f=>{f.broker.behavior='REJECT';return (await f.fill()).state==='REJECTED';});
      await check('Partial equity fill and remainder cancellation',async f=>{f.broker.behavior='PARTIAL';const p=await f.fill({...exampleProposal(),quantity:2});await f.proposals.cancel(p.id,'SIMULATION');return f.proposals.get(p.id).state==='CANCELLED'&&f.ledger.getPosition(p.strategy,p.symbol)?.quantity===1;});
      await check('Pending order cancellation releases reservations',async f=>{f.broker.behavior='PENDING';const p=await f.fill();await f.proposals.cancel(p.id,'SIMULATION');return f.allocation.state(p.strategy).reservedCapital===0;});
      for(const [name,mark] of [['Profit exit',80],['Stop-triggered validated exit',40]] as const)await check(name,async f=>{await f.fill();f.broker.quotePatch={price:mark,bid:mark,ask:mark+.01};const close=await f.fill({...exampleProposal(),positionEffect:'CLOSE',side:'SELL',limitPrice:mark});return close.state==='FILLED'&&(mark>60?f.ledger.getRealizedPnl()>0:f.ledger.getRealizedPnl()<0);});
      const riskCases:Array<[string,string,unknown,string]>=[['Blocked symbol','blockedSymbols',['RKLB'],'CONFIG_SYMBOL'],['Max position','maxPositionPercent',.01,'CONFIG_SIZING'],['Gross exposure','maxGrossExposurePercent',.01,'CONFIG_GROSS_NET'],['Premium risk','maxPremiumRiskPercent',.001,'CONFIG_PREMIUM_RISK'],['DTE rule','minDTE',100,'CONFIG_DTE'],['Pending order limit','maxPendingOrders',0,'CONFIG_PENDING_LIMIT'],['Global trading disabled','tradingEnabled',false,'CONFIG_TRADING_ENABLED']];
      for(const [name,key,value,code] of riskCases)await check(name,async f=>{patch(f,key,value);return rejection(f,key==='maxPremiumRiskPercent'||key==='minDTE'?f.option():exampleProposal(),code);});
      await check('Insufficient sleeve capital isolated',async f=>{f.db.raw.prepare("UPDATE strategy_cash SET balance=0 WHERE strategy_id='AGGRESSIVE_STOCKS'").run();return rejection(f,exampleProposal(),'CASH_COLLATERAL');});
      await check('Insufficient account buying power',async f=>{f.broker.accountPatch={buyingPower:0};return rejection(f,exampleProposal(),'CASH_COLLATERAL');});
      await check('Stale quote',async f=>{f.broker.quotePatch={asOf:new Date(Date.now()-120000).toISOString()};return rejection(f,exampleProposal(),'QUOTE');});
      await check('Stale proposal',f=>rejection(f,{...exampleProposal(),createdAt:new Date(Date.now()-3600000).toISOString()},'PROPOSAL_FRESH'));
      await check('Stale portfolio',async f=>{f.broker.accountPatch={asOf:new Date(Date.now()-3600000).toISOString()};return rejection(f,exampleProposal(),'CONFIG_PORTFOLIO_FRESH');});
      await check('Stale reconciliation',async f=>{await f.proposals.reconcile();f.db.setSetting('last_reconciliation_at',new Date(Date.now()-3600000).toISOString());const p=f.proposals.create(exampleProposal(),'SIM');return (await f.proposals.risk(p.id)).checks.some(c=>c.code==='CONFIG_RECONCILIATION_FRESH'&&!c.ok);});
      await check('Stale research',async f=>{const p=await f.ready();const r=JSON.parse(f.proposals.row(p.id).research_json!);r.items.forEach((i:{observedAt:string})=>i.observedAt=new Date(Date.now()-7*86400000).toISOString());f.db.raw.prepare('UPDATE proposals SET research_json=? WHERE id=?').run(JSON.stringify(r),p.id);return !(await f.proposals.risk(p.id)).approved;});
      await check('Long put Level 2 entry',async f=>(await f.fill(f.option('LONG_PUT'))).state==='FILLED');
      await check('Naked covered call rejected',f=>rejection(f,f.option('COVERED_CALL'),'SAME_SLEEVE_COVERAGE'));
      await check('Covered call requires same-sleeve 100 shares',async f=>{const o=f.ledger.createOrder({idempotencyKey:'covered-fixture',strategyId:'OPTIONS',symbol:'TEST',side:'BUY',quantity:100,orderType:'MARKET',mode:'SIMULATION',source:'FIXTURE'});f.ledger.applyFill({brokerFillId:'covered-shares',orderId:o,quantity:100,price:10,fees:0,executedAt:nowIso()});return (await f.fill(f.option('COVERED_CALL'))).state==='FILLED';});
      await check('CSP full strike collateral',async f=>{await f.fill(f.option('CASH_SECURED_PUT'));return f.allocation.state('OPTIONS').reservedCapital===1000;});
      await check('Insufficient CSP collateral',async f=>{f.db.raw.prepare("UPDATE strategy_cash SET balance=500 WHERE strategy_id='OPTIONS'").run();return rejection(f,f.option('CASH_SECURED_PUT'),'CASH_COLLATERAL');});
      await check('Excessive option spread',async f=>{f.broker.quotePatch={bid:.5,ask:1.5};return rejection(f,f.option(),'CONFIG_OPTION_SPREAD');});
      await check('Low open interest',async f=>{f.broker.quotePatch={openInterest:0};return rejection(f,f.option(),'CONFIG_OPEN_INTEREST');});
      await check('Contract partial fill',async f=>{f.broker.behavior='PARTIAL';const input=f.option();input.quantity=2;input.option!.contracts=2;return (await f.fill(input)).state==='PARTIALLY_FILLED';});
      await check('Trusted telemetry leaves absent Greeks unavailable',async f=>{const p=await f.fill(f.option());f.analytics.recordOption(p.option!.optionId,await f.broker.quote(p));return f.analytics.optionDetail(p.option!.optionId).delta===null;});
      await check('Synthetic option mark, theta and IV movement recorded with provenance',async f=>{const p=await f.fill(f.option());f.broker.quotePatch={price:1.5,bid:1.49,ask:1.51,theta:-.02,iv:.35,delta:.6,underlyingPrice:12};f.analytics.recordOption(p.option!.optionId,await f.broker.quote(p));f.db.raw.prepare('UPDATE option_positions SET mark_price=1.5').run();const t=f.analytics.optionDetail(p.option!.optionId);return t.theta===-.02&&t.iv===.35&&t.unrealizedPnL!>0;});
      for(const mark of [.5,1.5])await check(mark<1?'Losing option close':'Profitable option close',async f=>{const input=f.option();await f.fill(input);f.broker.quotePatch={price:mark,bid:mark,ask:mark+.01};const p=await f.fill({...input,positionEffect:'CLOSE',side:'SELL',limitPrice:mark});return p.state==='FILLED'&&(mark<1?f.ledger.getRealizedPnl()<0:f.ledger.getRealizedPnl()>0);});
      for(const type of ['EXPIRATION','ASSIGNMENT','EXERCISE'] as const)await check('Option '+type+' reviewed economic event',async f=>{const input=f.option(type==='ASSIGNMENT'?'CASH_SECURED_PUT':'LONG_CALL');await f.fill(input);const observedAt=type==='EXPIRATION'?input.option!.expiration+'T21:00:00.000Z':nowIso();f.events.ingest({id:'event-'+type,type,accountId:'SIMULATION',strategy:'OPTIONS',optionId:input.option!.optionId,contracts:1,observedAt,sourceReference:'Synthetic verified lifecycle fixture'},'SIM');f.events.apply('event-'+type,'SIM','APPLY VERIFIED BROKER EVENT','Reviewed synthetic lifecycle event details');return f.allocation.state('OPTIONS').options.length===0&&(type==='EXPIRATION'||f.ledger.getPosition('OPTIONS','TEST')?.quantity===100);});
      await check('Unsupported Level 3 strategy rejected by schema',f=>!proposalSchema.safeParse({...f.option(),option:{...f.option().option!,strategy:'IRON_CONDOR'}}).success);
      await check('Duplicate execution cannot place twice',async f=>{const p=await f.fill();await f.proposals.execute(p.id,'SIM');return f.broker.calls===1;});
      await check('Duplicate fill cannot change cash twice',async f=>{const p=await f.fill();const row=f.db.raw.prepare('SELECT * FROM fills LIMIT 1').get() as {broker_fill_id:string;quantity:number;price:number;fees:number;executed_at:string};const ex=f.db.raw.prepare('SELECT broker_order_id FROM executions_v2 WHERE proposal_id=?').get(p.id) as {broker_order_id:string};const cash=f.ledger.getCash(p.strategy);f.proposals.applyFill(p.id,{id:row.broker_fill_id,brokerOrderId:ex.broker_order_id,quantity:row.quantity,price:row.price,fees:row.fees,executedAt:row.executed_at});return cash===f.ledger.getCash(p.strategy);});
      await check('Manual approval is mandatory',async f=>{const p=await f.ready();try{await f.proposals.execute(p.id,'SIM');return false;}catch{return f.broker.calls===0;}});
      await check('Agent cannot bypass app-tool allowlist',async f=>{const a=new PersistentTradingAgent(f.db,f.proposals),s=a.create('SIM','AUTONOMOUS');const result=await a.tool(s.id,'SIM','turn','user','place_equity_order',{});return Object.hasOwn(result as object,'error')&&f.broker.calls===0;});
      await check('Agent unavailable leaves deterministic reconciliation working',async f=>{const a=new PersistentTradingAgent(f.db,f.proposals,{respond:async()=>{throw new Error('Synthetic OpenAI outage');}}),s=a.create('SIM');await a.chat(s.id,'SIM','Explain the account');return (await f.proposals.reconcile()).clear;});
      for(const behavior of ['TIMEOUT','UNKNOWN'] as const)await check('Broker '+behavior+' never replayed',async f=>{f.broker.behavior=behavior;try{await f.fill();}catch{/* Expected uncertain placement. */}const p=f.proposals.list()[0]!;try{await f.proposals.execute(p.id,'SIM');}catch{/* Must never resend. */}return f.proposals.get(p.id).state==='RECONCILIATION_REQUIRED'&&f.broker.calls===1&&!(await f.proposals.reconcile()).clear;});
      await check('Broker outage pauses reconciliation',async f=>{f.broker.account=async()=>{throw new Error('Synthetic MCP outage');};try{await f.proposals.reconcile();return false;}catch{return !f.db.getSetting('reconciliation_clear',true)&&f.db.getSetting('global_pause',false);}});
      await check('Market data unavailable blocks risk',async f=>{await f.proposals.reconcile();f.broker.quote=async()=>{throw new Error('Synthetic market-data outage');};try{await f.proposals.risk(f.proposals.create(exampleProposal(),'SIM').id);return false;}catch{return f.broker.calls===0;}});
      await check('Reconciliation mismatch and reconnect recovery',async f=>{f.broker.accountPatch={cash:1};const bad=await f.proposals.reconcile();f.broker.accountPatch={};return !bad.clear&&(await f.proposals.reconcile()).clear;});
      await check('Pause and resume sleeve',async f=>{f.db.setStrategyEnabled('AGGRESSIVE_STOCKS',false,'SIM','Scenario pause');const blocked=await rejection(f,exampleProposal(),'SLEEVE_ENABLED');f.db.setStrategyEnabled('AGGRESSIVE_STOCKS',true,'SIM','Reviewed scenario resume');return blocked&&!!f.db.getStrategy('AGGRESSIVE_STOCKS')?.enabled;});
      await check('Global STOP blocks new orders without agent',async f=>{f.db.setSetting('stopped',true);return rejection(f,exampleProposal(),'MAINTENANCE_STOP');});
      await check('60% emergency sleeve kill remains latched',f=>{f.allocation.state('SAFE_LONG_TERM');f.db.raw.prepare("UPDATE strategy_cash SET balance=100 WHERE strategy_id='SAFE_LONG_TERM'").run();return f.allocation.state('SAFE_LONG_TERM').killed;});
      await check('Risk change diff and rollback',f=>{const original=f.risk.current().config;patch(f,'maxOrderNotional',20);const changed=f.risk.current().version;f.risk.apply(original,changed,'SIM','Explicit synthetic rollback configuration','APPLY RISK CONFIGURATION');return f.risk.current().config.global.maxOrderNotional===original.global.maxOrderNotional&&f.risk.history().length===2;});
      await check('Transferred holding and basis assigned explicitly',f=>{f.events.ingest({id:'transfer',type:'TRANSFER_EQUITY',accountId:'SIMULATION',strategy:'SAFE_LONG_TERM',symbol:'TRANSFER',quantity:2,averageCost:10,mark:12,assetClass:'EQUITY',observedAt:nowIso(),sourceReference:'Synthetic broker transfer fixture'},'SIM');f.events.apply('transfer','SIM','APPLY VERIFIED BROKER EVENT','Verified synthetic transfer cost basis');return f.ledger.getPosition('SAFE_LONG_TERM','TRANSFER')?.averageCost===10;});
      await check('Deposit and withdrawal are external flows, not returns',f=>{f.analytics.snapshot('START');for(const [id,amount] of [['deposit',100],['withdrawal',-100]] as const){f.events.ingest({id,type:'CASH_FLOW',accountId:'SIMULATION',strategy:'SAFE_LONG_TERM',amount,observedAt:nowIso(),sourceReference:'Synthetic cash flow fixture'},'SIM');f.events.apply(id,'SIM','APPLY VERIFIED BROKER EVENT','Verified synthetic cash flow review');}return f.analytics.performance('2000-01-01').pnl===0;});
      await check('Corporate stock split preserves equity and basis',async f=>{await f.fill();const before=f.ledger.getPosition('AGGRESSIVE_STOCKS','RKLB')!;f.events.ingest({id:'split',type:'SPLIT',accountId:'SIMULATION',strategy:'AGGRESSIVE_STOCKS',symbol:'RKLB',ratio:2,observedAt:nowIso(),sourceReference:'Synthetic split fixture'},'SIM');f.events.apply('split','SIM','APPLY VERIFIED BROKER EVENT','Verified synthetic stock split review');return f.ledger.getPosition('AGGRESSIVE_STOCKS','RKLB')!.marketValue===before.marketValue;});
      await check('Scheduler holiday and duplicate slot protection',async f=>{const scheduler=new PersistedTradingScheduler(f.db,f.proposals,async()=>{});await scheduler.tick(new Date('2026-07-03T13:35:00Z'));return !(f.db.raw.prepare('SELECT last_run_at FROM scheduler_jobs_v2 WHERE last_run_at IS NOT NULL').get());});
      await check('File DB restart recovers pending order without replay',async()=>{const path=join(this.directory,id+'-restart.db'),before=fixture(path);before.broker.behavior='PENDING';const p=await before.fill();before.db.close();const after=fixture(path);try{await after.proposals.execute(p.id,'RESTART');return after.proposals.get(p.id).state==='BROKER_ACCEPTED'&&after.broker.calls===0&&(await after.proposals.reconcile()).clear;}finally{after.db.close();}});
      await check('Duplicate proposal client key cannot create two executions',async f=>{const p=await f.fill();for(let i=0;i<3;i++)await f.proposals.execute(p.id,'SIM');return (f.db.raw.prepare('SELECT COUNT(*) AS n FROM executions_v2 WHERE proposal_id=?').get(p.id) as {n:number}).n===1;});
      await check('Daily realized loss blocks entry',async f=>{const p=await f.fill();f.broker.quotePatch={price:5,bid:5,ask:5.01};await f.fill({...exampleProposal(),side:'SELL',positionEffect:'CLOSE',limitPrice:5});f.broker.quotePatch={};return await rejection(f,{...exampleProposal(),symbol:'NVDA'},'CONFIG_DAILY_LOSS')&&p.state==='FILLED';});
      await check('Simulation namespace cannot access live placement graph',f=>f.broker instanceof SimulationTradingBroker&&f.db.getMode()==='SIMULATION'&&!('liveBroker' in f),true);
      for(const price of [65,58,72]){main.ledger.markPrices([{symbol:'RKLB',price}]);main.db.raw.prepare('UPDATE option_positions SET mark_price=? WHERE contracts>0').run(price/60);main.analytics.snapshot('SYNTHETIC_MARK_MOVEMENT');emit('PORTFOLIO','Accelerated fixture mark '+price,null,{account:await main.broker.account(),sleeves:SLEEVES.map(s=>main.allocation.state(s)),chart:main.analytics.series('ALL')});if(control.speed)await new Promise(r=>setTimeout(r,500/control.speed));}
      main.analytics.snapshot('END');emit('PORTFOLIO','Account and sleeve snapshots',null,{account:await main.broker.account(),sleeves:SLEEVES.map(s=>main.allocation.state(s)),chart:main.analytics.series('ALL')});
      for(const kind of ['DAILY_REPORT','WEEKLY_REPORT']){const body=main.analytics.report(kind);main.notifications.emit(id+kind,kind,'INFO',{summary:'Synthetic '+kind,report:body});emit('REPORT',kind,null,body);}
      main.notifications.emit(id+'risk','KILL_SWITCH','CRITICAL',{summary:'Synthetic risk alert'});main.notifications.emit(id+'recon','RECONCILIATION_FAILURE','CRITICAL',{summary:'Synthetic reconciliation alert'});
      await check('Reports, notifications and charts persisted',f=>f.analytics.series('ALL').points.length>=2&&f.notifications.list().length>=4&&(f.db.raw.prepare('SELECT COUNT(*) AS n FROM trading_reports').get() as {n:number}).n>=2,true);
      const ok=assertions.every(a=>a.passed)&&!control.cancelled,result={ok,status:control.cancelled?'CANCELLED':ok?'SYSTEM TEST PASSED':'SYSTEM TEST FAILED',assertions,passed:assertions.filter(a=>a.passed).length,failed:assertions.filter(a=>!a.passed).length,elapsedMs:Date.now()-started,configHash:evidenceHash,richRiskHash:configHash(config),liveBrokerCalls:0,externalRequests:0,simulated:true,portfolio:await main.broker.account(),charts:main.analytics.series('ALL'),notifications:main.notifications.list(),limitations:['Fixture events test economic ledger mechanics, not broker deliverable/tax-basis contracts.','Restart recovery acceptance must additionally run on physical Pi.','No real AI research, webhook delivery, SMS or broker connectivity is claimed.']};
      emit('FINISHED',result.status,ok,result);this.db.raw.prepare('UPDATE simulation_runs SET status=?,result_json=?,finished_at=? WHERE id=?').run(control.cancelled?'CANCELLED':ok?'PASSED':'FAILED',JSON.stringify(result),nowIso(),id);
      if(ok&&evidenceHash===configurationEvidenceHash(this.db))this.db.setSetting('full_simulation_evidence',{id,configHash:evidenceHash,at:nowIso()});
    }finally{main.db.close();this.active.delete(id);}
  }
}
